import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.55.0";
const URL=Deno.env.get('SUPABASE_URL')||'';const KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';const TOKEN=Deno.env.get('TELEGRAM_BOT_TOKEN')||Deno.env.get('BOT_TOKEN')||'';const sb=createClient(URL,KEY,{auth:{persistSession:false,autoRefreshToken:false}});
const json=(d:any,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{'content-type':'application/json'}});
async function tg(method:string,payload:any){const r=await fetch(`https://api.telegram.org/bot${TOKEN}/${method}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const j=await r.json().catch(()=>({ok:false,description:'Bad Telegram response'}));if(!r.ok||!j.ok)throw new Error(j.description||`${method} failed`);return j.result}
async function secret(){const{data}=await sb.rpc('get_bot_internal_secret',{p_name:'adsreward_telegram_webhook_secret'});return String(data||'')}
function same(a:string,b:string){if(!a||a.length!==b.length)return false;let x=0;for(let i=0;i<a.length;i++)x|=a.charCodeAt(i)^b.charCodeAt(i);return x===0}
async function isAdmin(id:number){const{data}=await sb.from('settings').select('value').eq('key','bot_admin_telegram_ids').maybeSingle();const ids=String(data?.value||Deno.env.get('ADMIN_TELEGRAM_ID')||'2139807311').split(',').map((x:string)=>Number(x.trim())).filter(Number.isSafeInteger);return ids.includes(id)}
async function getSess(id:number){const{data}=await sb.from('group_broadcast_sessions').select('*').eq('admin_telegram_id',id).maybeSingle();return data}
async function setSess(id:number,patch:any){await sb.from('group_broadcast_sessions').upsert({admin_telegram_id:id,...patch,updated_at:new Date().toISOString()},{onConflict:'admin_telegram_id'})}
async function clearSess(id:number){await sb.from('group_broadcast_sessions').delete().eq('admin_telegram_id',id)}
async function send(chat:number,text:string,kb:any[][]=[]){return tg('sendMessage',{chat_id:chat,text,disable_web_page_preview:true,reply_markup:{inline_keyboard:kb}})}
async function ack(id:string,text=''){try{await tg('answerCallbackQuery',{callback_query_id:id,text})}catch{}}
function buttonMarkup(s:any){return s?.button_text&&s?.button_url?{inline_keyboard:[[{text:s.button_text,url:s.button_url}]]}:undefined}
async function preview(chat:number,s:any){const{count}=await sb.from('telegram_bot_chats').select('*',{count:'exact',head:true}).in('chat_type',['group','supergroup']).eq('is_active',true).eq('can_send_messages',true);await tg('sendMessage',{chat_id:chat,text:`📢 Group Broadcast Preview\n\n${s.message_text}\n\nTargets: ${count||0} active groups`,disable_web_page_preview:true,reply_markup:{inline_keyboard:[...[...(s.button_text&&s.button_url?[[{text:s.button_text,url:s.button_url}]]:[])],...[[{text:'✅ Confirm Broadcast',callback_data:'gcb:confirm'},{text:'❌ Cancel',callback_data:'gcb:cancel'}]]]}})}
Deno.serve(async(req)=>{try{if(req.method!=='POST')return json({handled:false});const expected=await secret();if(!same(expected,req.headers.get('x-telegram-bot-api-secret-token')||''))return json({handled:false},401);const body=await req.json().catch(()=>({}));const msg=body?.message;const cb=body?.callback_query;const from=msg?.from||cb?.from;const chat=msg?.chat||cb?.message?.chat;if(!from||!chat)return json({handled:false});const uid=Number(from.id);if(!await isAdmin(uid))return json({handled:false});const text=String(msg?.text||'').trim();const cmd=text.split(/\s+/)[0].split('@')[0].toLowerCase();const data=String(cb?.data||'');let s=await getSess(uid);
if(cmd==='/gcbroad'){await clearSess(uid);await setSess(uid,{step:'message'});await send(chat.id,'📢 Group Broadcast\n\nSend the message you want to broadcast to all active group chats.\n\nYou can send any text message.');return json({handled:true})}
if(data.startsWith('gcb:')){await ack(cb.id);s=await getSess(uid);if(!s){await send(chat.id,'Broadcast session expired. Use /gcbroad again.');return json({handled:true})}if(data==='gcb:cancel'){await clearSess(uid);await send(chat.id,'❌ Group broadcast cancelled.');return json({handled:true})}if(data==='gcb:add'){await setSess(uid,{...s,step:'button_text'});await send(chat.id,'🔘 Send the button text.');return json({handled:true})}if(data==='gcb:skip'){await setSess(uid,{...s,step:'confirm'});await preview(chat.id,{...s,button_text:null,button_url:null});return json({handled:true})}if(data==='gcb:confirm'){const{data:groups}=await sb.from('telegram_bot_chats').select('chat_id,chat_title').in('chat_type',['group','supergroup']).eq('is_active',true).eq('can_send_messages',true);const targets=groups||[];const markup=buttonMarkup(s);let sent=0,failed=0;for(let i=0;i<targets.length;i+=10){const batch=targets.slice(i,i+10);const rs=await Promise.allSettled(batch.map((g:any)=>tg('sendMessage',{chat_id:g.chat_id,text:s.message_text,disable_web_page_preview:true,...(markup?{reply_markup:markup}:{})})));for(const r of rs)r.status==='fulfilled'?sent++:failed++;}await sb.from('admin_logs').insert({admin_telegram_id:uid,action:'group_broadcast',details:{sent,failed,total:targets.length,hasButton:Boolean(s.button_text&&s.button_url)}});await clearSess(uid);await send(chat.id,`✅ Group Broadcast Complete\n\nSent: ${sent}\nFailed: ${failed}\nTotal groups: ${targets.length}`);return json({handled:true})}}
if(!msg)return json({handled:false});s=await getSess(uid);if(!s)return json({handled:false});if(s.step==='message'){if(!text)return send(chat.id,'Please send a text message.'),json({handled:true});await setSess(uid,{...s,step:'button_choice',message_text:text});await send(chat.id,'Message saved.\n\nDo you want to add a button?',[[{text:'➕ Add Button',callback_data:'gcb:add'},{text:'➡️ Send Without Button',callback_data:'gcb:skip'}]]);return json({handled:true})}if(s.step==='button_text'){if(!text)return send(chat.id,'Please send button text.'),json({handled:true});await setSess(uid,{...s,step:'button_url',button_text:text.slice(0,64)});await send(chat.id,'🔗 Now send the button URL.');return json({handled:true})}if(s.step==='button_url'){try{const u=new URL(text);if(!['http:','https:','tg:'].includes(u.protocol))throw new Error()}catch{await send(chat.id,'Invalid URL. Send a valid https://, http://, or tg:// link.');return json({handled:true})}await setSess(uid,{...s,step:'confirm',button_url:text});await preview(chat.id,{...s,button_url:text});return json({handled:true})}return json({handled:false})}catch(e){console.error('telegram-group-broadcast',e);return json({handled:false,error:(e as Error).message},500)}});
