import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.55.0";
const URL=Deno.env.get('SUPABASE_URL')||'';
const KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';
const sb=createClient(URL,KEY,{auth:{persistSession:false,autoRefreshToken:false}});
const json=(d:any,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{'Content-Type':'application/json'}});
const PVP_CMDS=new Set(['/pvp','/games','/credits','/convert','/challenge','/pvpstats','/pvpboard','/matches','/pvpsettings']);
const PVP_DICE:Record<string,string>={'🎲':'dice','🎯':'darts','🏀':'basketball','⚽':'football','🎳':'bowling','🎰':'slots'};
async function forward(name:string,body:any,headers:Headers){const h:Record<string,string>={'Content-Type':'application/json'};for(const k of ['x-telegram-bot-api-secret-token','x-bot-worker-token']){const v=headers.get(k);if(v)h[k]=v;}return fetch(`${URL}/functions/v1/${name}`,{method:'POST',headers:h,body:JSON.stringify(body)});}
async function pvpCandidate(body:any){const cb=body?.callback_query;if(String(cb?.data||'').startsWith('pvp'))return true;const msg=body?.message;if(!msg?.from||msg.from.is_bot)return false;const cmd=String(msg.text||'').trim().split(/\s+/)[0].split('@')[0].toLowerCase();if(PVP_CMDS.has(cmd))return true;const chat=Number(msg.chat?.id),tgid=Number(msg.from?.id);if(!Number.isSafeInteger(chat)||chat>=0||!Number.isSafeInteger(tgid))return false;const{data:u}=await sb.from('users').select('id').eq('telegram_id',tgid).maybeSingle();if(!u?.id)return false;if(msg.dice?.emoji&&PVP_DICE[msg.dice.emoji]){const{data:m}=await sb.from('pvp_matches').select('id').eq('group_id',chat).eq('status','in_progress').eq('game_key',PVP_DICE[msg.dice.emoji]).or(`host_user_id.eq.${u.id},opponent_user_id.eq.${u.id}`).limit(1);if(m?.length)return true;}if(/^\d+$/.test(String(msg.text||'').trim())){const{data:f}=await sb.from('pvp_pending_flows').select('game_key,expires_at').eq('group_id',chat).eq('user_id',u.id).maybeSingle();if(f?.game_key&&new Date(f.expires_at).getTime()>Date.now())return true;}return false;}
Deno.serve(async(req:Request)=>{try{if(req.method==='GET')return json({success:true,service:'telegram-router',version:'v10-permanent-single-router'});if(req.method!=='POST')return json({success:false,error:'Method not allowed'},405);const body=await req.json().catch(()=>({}));if(body?.action==='sync-webhook'){const r=await forward('telegram-router-core',body,req.headers);return new Response(await r.text(),{status:r.status,headers:{'Content-Type':'application/json'}});}if(await pvpCandidate(body)){const r=await forward('telegram-router-core',body,req.headers);return new Response(await r.text(),{status:r.status,headers:{'Content-Type':'application/json'}});}try{const g=await forward('telegram-giveaway-v2',body,req.headers);const j=await g.json().catch(()=>({handled:false}));if(g.ok&&j?.handled)return json({success:true,handledBy:'telegram-giveaway-v2',...j});}catch(e){console.error('giveaway-v2 forward failed',e)}const r=await forward('telegram-router-core',body,req.headers);return new Response(await r.text(),{status:r.status,headers:{'Content-Type':'application/json'}});}catch(e){console.error('telegram-router v10',e);return json({success:false,error:(e as Error).message},500)}});