// @ts-nocheck
import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.55.0";
const URL=Deno.env.get('SUPABASE_URL')||'',KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'',TOKEN=Deno.env.get('TELEGRAM_BOT_TOKEN')||Deno.env.get('BOT_TOKEN')||'',APP='https://star-rewards-hub.vercel.app',GROUP_APP='https://t.me/Adsrewartsbot/app';
const sb=createClient(URL,KEY,{auth:{persistSession:false,autoRefreshToken:false}}),J=(d:any,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{'Content-Type':'application/json'}}),E=(v:any)=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;'),F=(n:any)=>Number(n||0).toLocaleString('en-US');
function eq(a:string,b:string){if(!a||a.length!==b.length)return false;let x=0;for(let i=0;i<a.length;i++)x|=a.charCodeAt(i)^b.charCodeAt(i);return x===0}
async function sec(){const{data,error}=await sb.rpc('get_bot_internal_secret',{p_name:'adsreward_bot_worker_token'});if(error||!data)throw error||new Error('worker secret missing');return String(data)}
async function tg(m:string,p:any){const r=await fetch(`https://api.telegram.org/bot${TOKEN}/${m}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)}),b=await r.json().catch(()=>({ok:false}));if(!r.ok||!b.ok)throw new Error(String(b.description||m));return b.result}
const web=(text='🚀 Open AdsReward',page='home')=>({text,web_app:{url:`${APP}/?page=${encodeURIComponent(page)}`}}),K=(text='🚀 Open AdsReward',page='home')=>[[web(text,page)]];
async function settings(){const{data,error}=await sb.from('settings').select('key,value');if(error)throw error;return Object.fromEntries((data||[]).map((x:any)=>[x.key,String(x.value)]))}
const on=(s:any,k:string,f=true)=>s[k]===undefined?f:!['false','0','off','no','disabled'].includes(String(s[k]).toLowerCase());
function enabled(t:string,s:any,p:any){if(!on(s,'bot_enabled',true))return false;const m:any={welcome:'bot_welcome_enabled',task_complete:'bot_task_alerts_enabled',new_task:'bot_new_task_alerts_enabled',task_expiring:'bot_task_expiry_alerts_enabled',farm_ready:'bot_farm_alerts_enabled',farm_followup:'bot_farm_followup_enabled',daily_login:'bot_daily_login_enabled',streak_warning:'bot_streak_warning_enabled',daily_streak:'bot_streak_alerts_enabled',ad_reset:'bot_ad_reset_enabled',ads_progress:'bot_ad_progress_enabled',ads_few_remaining:'bot_ad_progress_enabled',ads_limit_complete:'bot_ad_progress_enabled',withdraw_submitted:'bot_withdrawal_alerts_enabled',withdraw_complete:'bot_withdrawal_alerts_enabled',withdraw_rejected:'bot_withdrawal_alerts_enabled',admin_withdrawal:'bot_admin_withdrawal_alerts_enabled',new_referral:'bot_referral_alerts_enabled',referral_qualified:'bot_referral_alerts_enabled',referral_reward:'bot_referral_alerts_enabled',promo_alert:'bot_promo_alerts_enabled',promo_claimed:'bot_promo_alerts_enabled',contest_alert:'bot_contest_alerts_enabled',rank_up:'bot_rank_up_alerts_enabled',balance_milestone:'bot_balance_milestones_enabled',withdraw_unlocked:'bot_withdrawal_unlocked_enabled',withdraw_close:'bot_withdrawal_goal_enabled',daily_report:'bot_daily_reports_enabled',weekly_report:'bot_weekly_reports_enabled',smart_rewards:'bot_smart_reminders_enabled',inactive_today:'bot_inactivity_enabled',inactive_3d:'bot_inactivity_enabled',inactive_7d:'bot_inactivity_enabled',tip_sent:'bot_enabled',tip_received:'bot_enabled',giveaway_won:'bot_enabled',giveaway_group_winner:'bot_enabled',pvp_challenge:'bot_pvp_alerts_enabled',pvp_win:'bot_pvp_alerts_enabled',pvp_loss:'bot_pvp_alerts_enabled',pvp_channel_challenge:'bot_pvp_alerts_enabled',account_restricted:'bot_enabled',account_restored:'bot_enabled',maintenance_on:'bot_enabled',maintenance_off:'bot_enabled'};if(t==='mission_completed')return on(s,p?.missionType==='weekly'?'bot_weekly_missions_enabled':'bot_daily_missions_enabled',true);if(t==='reward_unlocked')return on(s,p?.rewardType==='comeback'?'bot_comeback_reward_enabled':'bot_achievement_alerts_enabled',true);return on(s,m[t]||'bot_enabled',true)}
function V(e:any){const p=e.payload||{},t=e.event_type;switch(t){
case'task_complete':return[`✅ <b>Task Completed</b>\n\n📋 ${E(p.taskName||'Task')}\n🎁 +${F(p.reward)} ADR\n💎 Balance: <b>${F(p.balance)} ADR</b>`,K('🎯 More Tasks','tasks')];
case'new_task':return[`🆕 <b>New Task Available</b>\n\n📋 ${E(p.taskName||'Task')}\n🎁 Reward: <b>${F(p.reward)} ADR</b>`,K('🎯 Open Task','tasks')];
case'task_expiring':return[`⏳ <b>Task Expiring Soon</b>\n\n📋 ${E(p.taskName||'Task')}\n🎁 ${F(p.reward)} ADR`,K('🎯 Complete Task','tasks')];
case'farm_ready':return[`🌾 <b>Farm Ready</b>\n\nYour farming session is complete.\n🎁 <b>${F(p.reward)} ADR</b> ready to claim.`,K('🌾 Claim Now','home')];
case'farm_followup':return[`🌾 <b>Your Farm Is Waiting</b>\n\n${F(p.reward)} ADR is still ready to claim.`,K('🌾 Claim & Restart','home')];
case'daily_login':return[`🎁 <b>Daily Drop Ready</b>\n\n🔥 Day ${F(Number(p.day||0)+1)} streak\n🎁 <b>${F(p.reward)} ADR</b> available`,K('🎁 Claim Reward','home')];
case'streak_warning':return[`⏳ <b>Don't Lose Your Streak</b>\n\nYour <b>${F(p.day)}-day streak</b> is at risk.\n🎁 Next reward: <b>${F(p.reward)} ADR</b>`,K('🔥 Keep My Streak','home')];
case'daily_streak':return[`🔥 <b>Daily Reward Claimed</b>\n\n🎁 +${F(p.reward)} ADR\n🔥 Streak: <b>${F(p.day||p.streak)} days</b>`,K('🏠 Open AdsReward','home')];
case'ad_reset':return[`🔄 <b>Ads Are Available Again</b>\n\nYour daily ad limit has reset.`,K('📺 Watch Ads','tasks')];
case'ads_progress':return[`📺 <b>Ad Progress</b>\n\n${E(p.provider||'Ads')}: <b>${F(p.count)}/${F(p.limit)}</b> completed\n💎 Earned: <b>${F(p.earned)} ADR</b>`,K('📺 Keep Earning','tasks')];
case'ads_few_remaining':return[`🔥 <b>Almost Done</b>\n\n${p.provider?`${E(p.provider)} · `:''}Only <b>${F(p.remaining)}</b> ads remaining.${p.earned!==undefined?`\n💎 Earned: <b>${F(p.earned)} ADR</b>`:''}`,K('📺 Finish Goal','tasks')];
case'ads_limit_complete':return[`✅ <b>Daily Ads Complete</b>\n\n${p.provider?`${E(p.provider)}: `:''}<b>${F(p.count||p.limit)}/${F(p.limit||p.count)}</b> completed.${p.earned!==undefined?`\n💎 Earned: <b>${F(p.earned)} ADR</b>`:''}`,K('🚀 Open AdsReward','home')];
case'withdraw_submitted':return[`🕒 <b>Withdrawal Submitted</b>\n\nID: <code>${E(p.requestId||'')}</code>\n💎 ${F(p.points)} ADR\n${E(p.method||'')} · <b>${E(p.amount||'')}</b>\nStatus: <b>Pending</b>`,K('💳 View Withdrawal','wallet')];
case'withdraw_complete':return[`💸 <b>Withdrawal Paid</b>\n\n${p.requestId?`ID: <code>${E(p.requestId)}</code>\n`:''}${E(p.method||'')} · <b>${E(p.amount||'')}</b>\nStatus: <b>Paid</b>`,K('💳 Open Wallet','wallet')];
case'withdraw_rejected':return[`❌ <b>Withdrawal Rejected</b>\n\n${p.requestId?`ID: <code>${E(p.requestId)}</code>\n`:''}Reason: <b>${E(p.reason||'Rejected')}</b>\nADR Refund: <b>No</b>`,K('💳 View Details','wallet')];
case'admin_withdrawal':return[`💸 <b>New Withdrawal Request</b>\n\n${E(p.name||'User')} · <code>${E(p.telegramId||'')}</code>\n${E(p.method||'')} · <b>${E(p.amount||'')}</b>`,K('⚙️ Open Admin Panel','admin')];
case'new_referral':return[`👤 <b>New Referral</b>\n\n${p.name?`${E(p.name)} joined from your invite.\n`:''}Status: <b>Pending qualification</b>`,K('👥 View Referrals','refer')];
case'referral_qualified':case'referral_reward':return[`✅ <b>${t==='referral_qualified'?'Referral Qualified':'Referral Reward Added'}</b>\n\n${p.name?`👤 ${E(p.name)}\n`:''}${p.reward?`🎁 +${F(p.reward)} ADR\n`:''}${p.balance!==undefined?`💎 Balance: <b>${F(p.balance)} ADR</b>`:''}`,K('👥 View Referrals','refer')];
case'promo_alert':return[`🎟 <b>New Promo Code</b>\n\n${p.code?`Code: <code>${E(p.code)}</code>\n`:''}🎁 Reward: <b>${F(p.reward)} ADR</b>`,K('🎟 Claim Promo','home')];
case'promo_claimed':return[`🎉 <b>Promo Claimed</b>\n\n${p.code?`Code: <code>${E(p.code)}</code>\n`:''}🎁 +${F(p.reward)} ADR${p.balance!==undefined?`\n💎 Balance: <b>${F(p.balance)} ADR</b>`:''}`,K('💎 View Balance','profile')];
case'contest_alert':return[`🏆 <b>Contest Alert</b>\n\n${E(p.title||'AdsReward Contest')}`,K('🏆 View Contest','leaderboard')];
case'rank_up':return[`📈 <b>Level Up</b>\n\nYou reached <b>Level ${F(p.level||1)}</b>.`,K('👤 View Profile','profile')];
case'balance_milestone':return[`💎 <b>Balance Milestone</b>\n\nBalance: <b>${F(p.balance)} ADR</b>`,K('💎 View Balance','profile')];
case'withdraw_unlocked':return[`🎉 <b>Withdrawal Unlocked</b>\n\nBalance: <b>${F(p.balance)} ADR</b>\nYou now have enough ADR to withdraw.`,K('💸 Withdraw','wallet')];
case'withdraw_close':return[`💰 <b>You're Close to Withdrawal</b>\n\nBalance: <b>${F(p.balance)} ADR</b>\nMinimum: ${F(p.minimum)} ADR\nOnly <b>${F(p.remaining)} ADR</b> left.`,K('⚡ Earn More ADR','tasks')];
case'mission_completed':return[`🎯 <b>Mission Completed</b>\n\n🎁 +${F(p.reward)} ADR${p.balance!==undefined?`\n💎 Balance: <b>${F(p.balance)} ADR</b>`:''}`,K('🎯 View Missions','missions')];
case'reward_unlocked':return[`🏆 <b>Achievement Unlocked</b>\n\n🎁 +${F(p.reward)} ADR${p.balance!==undefined?`\n💎 Balance: <b>${F(p.balance)} ADR</b>`:''}`,K('🏆 View Achievements','achievements')];
case'balance_adjusted':return[`💎 <b>Balance Updated</b>\n\n${Number(p.delta||0)>=0?'➕':'➖'} ${Math.abs(Number(p.delta||0)).toLocaleString()} ADR\n${p.reason?`Reason: ${E(p.reason)}\n`:''}Balance: <b>${F(p.balance)} ADR</b>`,K('💎 View Balance','profile')];
case'daily_report':{const left=Math.max(0,Number(p.adLimit||0)-Number(p.ads||0));return[`📊 <b>Your Daily Progress</b>\n\n💎 Earned: <b>${F(p.earned)} ADR</b>\n📺 Ads: <b>${F(p.ads)}/${F(p.adLimit||0)}</b>${left>0&&left<=5?` · ${left} left`:''}\n🎯 Tasks: <b>${F(p.tasks)}</b>\n👥 Referrals: <b>${F(p.referrals)}</b>\n🌾 Farming: <b>${E(p.farming||'—')}</b>\n🔥 Daily Drop: <b>${p.checkin?'Claimed':'Waiting'}</b>`,K(left>0&&left<=5?'⚡ Finish Today’s Goals':'🚀 Continue Earning',left>0?'tasks':'home')];}
case'weekly_report':return[`📈 <b>Your Weekly Report</b>\n\n💎 Earned: <b>${F(p.earned)} ADR</b>\n📺 Ads: <b>${F(p.ads)}</b>\n🎯 Tasks: <b>${F(p.tasks)}</b>\n👥 Referrals: <b>${F(p.referrals)}</b>\n🌾 Farming claims: <b>${F(p.farming)}</b>${p.rank?`\n🏆 Rank: <b>#${F(p.rank)}</b>`:''}`,K('📊 View Stats','profile')];
case'smart_rewards':{const lines=[];if(p.farmReady)lines.push('🌾 Farming reward ready');if(p.dailyReady)lines.push('🔥 Daily Drop available');if(Number(p.newTasks)>0)lines.push(`🎯 New tasks: <b>${F(p.newTasks)}</b>`);if(Number(p.adsRemaining)>0)lines.push(`📺 Ads remaining: <b>${F(p.adsRemaining)}</b>`);return[`🎁 <b>Rewards Are Waiting</b>\n\n${lines.slice(0,4).join('\n')}\n\n💎 Balance: <b>${F(p.balance)} ADR</b>`,K('🚀 Collect Rewards','home')];}
case'inactive_today':return[`👋 <b>We Haven't Seen You Today</b>\n\nYour rewards are waiting.${p.streak?`\n🔥 ${F(p.streak)}-day streak active`:''}${p.farmReady?'\n🌾 Farming ready':''}\n📺 Ads available`,K('🚀 Continue Earning','home')];
case'inactive_3d':return[`👀 <b>Rewards Are Waiting</b>\n\nYou haven't earned for <b>3 days</b>.\n🎁 Come back and check today's earning opportunities.`,K('🚀 Start Earning','home')];
case'inactive_7d':return[`💎 <b>Come Back to AdsReward</b>\n\nIt's been <b>7 days</b> since your last activity.\nNew tasks, ads and rewards may be waiting.`,K('🚀 Come Back','home')];
case'tip_received':return[`🎁 <b>Tip Received</b>\n\nFrom: ${E(p.from||'User')}\n💎 +${F(p.amount)} ADR\nBalance: <b>${F(p.balance)} ADR</b>`,K('💎 View Balance','profile')];
case'tip_sent':return[`💸 <b>Tip Sent</b>\n\nTo: ${E(p.to||'User')}\nAmount: <b>${F(p.amount)} ADR</b>\nBalance: <b>${F(p.balance)} ADR</b>`,K('👤 View Profile','profile')];
case'giveaway_won':return[`🏆 <b>Giveaway Winner</b>\n\nGiveaway: <code>${E(p.publicId||'')}</code>\n🎁 +${F(p.reward)} ADR\nBalance: <b>${F(p.balance)} ADR</b>`,K('💎 View Balance','profile')];
case'giveaway_group_winner':return[`🎉 <b>Congrats ${E(p.username||'winner')}, you got it!</b>\n💎 <b>+${F(p.reward)} ADR</b> credited.`,[[{text:'🚀 Open AdsReward',url:GROUP_APP}]]];
case'pvp_challenge':return[`🎮 <b>PvP Challenge</b>\n\n${E(p.opponent||'A player')} challenged you.\n🎮 ${E(p.game||'Game')}\n💰 Bet: <b>${F(p.entry)} Game Credits</b>`,K('🎮 Open AdsReward','home')];
case'pvp_win':return[`🏆 <b>PvP Won</b>\n\nOpponent: ${E(p.opponent||'Player')}\nWinnings: <b>+${F(p.prize)} Game Credits</b>`,K('🎮 Open AdsReward','home')];
case'pvp_loss':return[`❌ <b>PvP Lost</b>\n\nWinner: ${E(p.opponent||'Player')}\nBet: <b>${F(p.entry)} Game Credits</b>`,K('🎮 Open AdsReward','home')];
case'pvp_channel_challenge':return[`⚔️ <b>PvP Challenge Live</b>\n\n🎮 ${E(p.game||'Game')}\n👤 Host: ${E(p.host||'Player')}\n💳 Entry: <b>${F(p.entry)} Game Credits</b>\n🏆 Prize: <b>${F(p.prize)} Game Credits</b>\n👥 Group: <b>${E(p.groupTitle||'Telegram Group')}</b>`,[[{text:'⚔️ Join Challenge',url:String(p.challengeUrl||GROUP_APP)}],[{text:'🚀 Open AdsReward',url:GROUP_APP}]]];
case'account_restricted':return[`🚫 <b>Account Restricted</b>\n\nReason: <b>${E(p.reason||'Account moderation')}</b>\nSome AdsReward features are unavailable.`,K('🆘 Open Support','support')];
case'account_restored':return[`✅ <b>Account Restored</b>\n\nYour AdsReward account is active again.`,K('🚀 Open AdsReward','home')];
case'maintenance_on':return[`🛠 <b>Maintenance Notice</b>\n\nAdsReward is temporarily under maintenance.\nYour balance and progress remain safe.`,[]];
case'maintenance_off':return[`✅ <b>AdsReward Is Back</b>\n\nMaintenance is complete. All services are available again.`,K('🚀 Open AdsReward','home')];
case'broadcast':return[`📢 <b>Announcement</b>\n\n${E(p.message||'')}`,K()];
case'welcome':return[`🎉 <b>Welcome to AdsReward${p.name?`, ${E(p.name)}`:''}</b>\n\n💎 Balance: <b>${F(p.balance)} ADR</b>`,K()];
default:return[`🔔 <b>AdsReward</b>\n\nOpen the Mini App for details.`,K()]}}
async function mark(e:any,ok:boolean,mid?:number,err?:string){const now=new Date().toISOString();if(ok)return void await sb.from('bot_outbox').update({status:'sent',sent_at:now,telegram_message_id:mid||null,locked_at:null,last_error:null,updated_at:now}).eq('id',e.id).eq('status','processing');const n=Number(e.attempts||0),blocked=/blocked by the user|chat not found|user is deactivated/i.test(err||'');await sb.from('bot_outbox').update({status:blocked||n>=8?'cancelled':'failed',next_attempt_at:blocked?null:new Date(Date.now()+Math.min(3600,30*2**Math.min(n,6))*1000).toISOString(),locked_at:null,last_error:String(err||'delivery failed').slice(0,1000),updated_at:now}).eq('id',e.id).eq('status','processing')}
Deno.serve(async(req)=>{try{if(req.method==='GET')return J({success:true,service:'telegram-alert-worker',version:'v5-complete-smart-alerts'});if(req.method!=='POST')return J({success:false},405);if(!eq(await sec(),req.headers.get('x-bot-worker-token')||''))return J({success:false,error:'unauthorized'},401);const s=await settings();const seed=await sb.rpc('seed_scheduled_bot_notifications');if(seed.error)console.error('seed notifications',seed.error.message);const smart=await sb.rpc('seed_smart_bot_notifications');if(smart.error)console.error('seed smart notifications',smart.error.message);const{data,error}=await sb.rpc('claim_bot_outbox',{p_limit:50});if(error)throw error;let sent=0,failed=0,cancelled=0;for(const e of data||[]){if(!enabled(e.event_type,s,e.payload||{})){await sb.from('bot_outbox').update({status:'cancelled',locked_at:null,updated_at:new Date().toISOString()}).eq('id',e.id);cancelled++;continue}try{const[v,k]=V(e);const payload:any={chat_id:e.recipient_telegram_id,text:v,parse_mode:'HTML',disable_web_page_preview:true};if(k?.length)payload.reply_markup={inline_keyboard:k};if(e.event_type==='giveaway_group_winner'&&Number(e.payload?.replyTo)>0)payload.reply_parameters={message_id:Number(e.payload.replyTo),allow_sending_without_reply:true};const r=await tg('sendMessage',payload);await mark(e,true,r.message_id);sent++}catch(x){await mark(e,false,undefined,String(x.message||x));failed++}}return J({success:true,claimed:(data||[]).length,sent,failed,cancelled})}catch(e){console.error('alert worker',e);return J({success:false,error:String(e.message||e)},500)}});