import React,{useEffect,useMemo,useState}from'react';
import{BadgeDollarSign,ChevronDown,ChevronUp,Database,IndianRupee,Search,ShieldCheck,WalletCards}from'lucide-react';
import{adminUpdateSetting}from'@/lib/api';

interface Props{settings:Record<string,string>;editSettings:Record<string,string>;setEditSettings:React.Dispatch<React.SetStateAction<Record<string,string>>>;onSave:(key:string)=>void;saving:string|null;}
type Meta={label:string;desc:string;type:'number'|'text'|'toggle';unit?:string};
const GROUPS=[
 ['Ads — Shared',['ad_reward_points','ad_init_delay_seconds','max_ads_per_hour']],
 ['Adsgram',['adsgram_max_ads_per_day','adsgram_cooldown_seconds','adsgram_block_id','adsgram_task_reward_points','adsgram_task_cooldown_seconds']],
 ['Monetag',['monetag_max_ads_per_day','monetag_cooldown_seconds']],
 ['GigaPub',['gigapub_max_ads_per_day','gigapub_cooldown_seconds']],
 ['Farm',['farm_reward_points','farm_duration_minutes']],
 ['Daily Drop',['daily_drop_base','daily_drop_increment','daily_drop_max_days','daily_drop_cooldown_seconds']],
 ['Daily Reward',['daily_bonus_base','daily_bonus_streak_multiplier']],
 ['Spin Wheel',['max_daily_spins','spin_cooldown_hours','spin_reward_min','spin_reward_max','spin_jackpot','spin_jackpot_chance']],
 ['Users & Referrals',['welcome_bonus','points_per_referral','referral_bonus_referred','max_referral_bonus']],
 ['Withdrawals & Rates',['withdrawal_enabled','withdraw_ton_enabled','withdraw_usdt_polygon_enabled','withdraw_upi_enabled','min_withdrawal_points','required_daily_ads','ton_conversion_rate','usdt_conversion_rate','inr_conversion_rate','max_pending_withdrawals','max_daily_withdrawals']],
 ['Leaderboard & Contest',['leaderboard_refresh_seconds','leaderboard_max_entries','contest_max_winners']],
 ['Promo Defaults',['promo_default_reward','promo_default_max_claims']],
 ['System',['maintenance_mode','bot_name','app_version','support_username','channel_username']],
]as const;
const M:Record<string,Meta>={
 ad_reward_points:{label:'Reward per Ad',desc:'ADR paid after a verified rewarded ad',type:'number',unit:'ADR'},ad_init_delay_seconds:{label:'First Ad Delay',desc:'Delay after app opens before ads can be used',type:'number',unit:'sec'},max_ads_per_hour:{label:'Ads per Provider / Hour',desc:'Independent rolling hourly safety limit for each provider',type:'number'},
 adsgram_max_ads_per_day:{label:'Adsgram Daily Limit',desc:'Set 0 to disable only Adsgram',type:'number',unit:'ads/day'},adsgram_cooldown_seconds:{label:'Adsgram Timer',desc:'Wait between Adsgram rewards',type:'number',unit:'sec'},adsgram_block_id:{label:'Adsgram Block ID',desc:'Adsgram rewarded block identifier',type:'text'},adsgram_task_reward_points:{label:'Adsgram Task Reward',desc:'ADR credited after a verified Adsgram task',type:'number',unit:'ADR'},adsgram_task_cooldown_seconds:{label:'Adsgram Task Refresh',desc:'Minimum wait before the next Adsgram task reward',type:'number',unit:'sec'},
 monetag_max_ads_per_day:{label:'Monetag Daily Limit',desc:'Set 0 to disable only Monetag',type:'number',unit:'ads/day'},monetag_cooldown_seconds:{label:'Monetag Timer',desc:'Wait between Monetag rewards',type:'number',unit:'sec'},
 gigapub_max_ads_per_day:{label:'GigaPub Daily Limit',desc:'Set 0 to disable only GigaPub',type:'number',unit:'ads/day'},gigapub_cooldown_seconds:{label:'GigaPub Timer',desc:'Wait between GigaPub rewards',type:'number',unit:'sec'},
 farm_reward_points:{label:'Farm Reward',desc:'ADR credited per completed farm',type:'number',unit:'ADR'},farm_duration_minutes:{label:'Farm Time',desc:'Minutes before Farm becomes claimable',type:'number',unit:'min'},daily_drop_base:{label:'Daily Drop Base',desc:'Day 1 reward',type:'number',unit:'ADR'},daily_drop_increment:{label:'Daily Drop Increment',desc:'Extra reward per streak day',type:'number',unit:'ADR/day'},daily_drop_max_days:{label:'Daily Drop Max Days',desc:'Maximum streak tier',type:'number',unit:'days'},daily_drop_cooldown_seconds:{label:'Drop Cooldown',desc:'Claim UI cooldown',type:'number',unit:'sec'},
 daily_bonus_base:{label:'Daily Reward Base',desc:'Base daily reward amount',type:'number',unit:'ADR'},daily_bonus_streak_multiplier:{label:'Daily Streak Bonus',desc:'Extra ADR per streak day',type:'number',unit:'ADR/day'},max_daily_spins:{label:'Spins per Day',desc:'Maximum spin attempts',type:'number'},spin_cooldown_hours:{label:'Spin Reset',desc:'Spin reset window',type:'number',unit:'hr'},spin_reward_min:{label:'Spin Min Reward',desc:'Minimum normal spin reward',type:'number',unit:'ADR'},spin_reward_max:{label:'Spin Max Reward',desc:'Maximum normal spin reward',type:'number',unit:'ADR'},spin_jackpot:{label:'Spin Jackpot',desc:'Jackpot reward',type:'number',unit:'ADR'},spin_jackpot_chance:{label:'Jackpot Chance',desc:'Jackpot probability',type:'number',unit:'%'},
 welcome_bonus:{label:'Welcome Bonus',desc:'ADR credited to a new user',type:'number',unit:'ADR'},points_per_referral:{label:'Referrer Reward',desc:'ADR reward for a valid referral',type:'number',unit:'ADR'},referral_bonus_referred:{label:'Referred User Bonus',desc:'ADR bonus for the referred user',type:'number',unit:'ADR'},max_referral_bonus:{label:'Max Referral Bonus',desc:'Maximum cumulative referral ADR bonus',type:'number',unit:'ADR'},
 withdrawal_enabled:{label:'All Withdrawals',desc:'Master switch for every payout method',type:'toggle'},withdraw_ton_enabled:{label:'GRAM (TON)',desc:'Enable or disable GRAM/TON withdrawals only',type:'toggle'},withdraw_usdt_polygon_enabled:{label:'USDT Polygon',desc:'Enable or disable USDT on Polygon only',type:'toggle'},withdraw_upi_enabled:{label:'INR UPI',desc:'Enable or disable INR UPI withdrawals only',type:'toggle'},min_withdrawal_points:{label:'Minimum Withdrawal',desc:'Minimum account ADR for a payout',type:'number',unit:'ADR'},required_daily_ads:{label:'Ads Required to Withdraw',desc:'Verified rewarded ads required today',type:'number',unit:'ads'},ton_conversion_rate:{label:'GRAM (Ex TON) Rate',desc:'ADR required per 1 TON/GRAM',type:'number',unit:'ADR/TON'},usdt_conversion_rate:{label:'USDT Polygon Rate',desc:'ADR required per 1 USDT',type:'number',unit:'ADR/USDT'},inr_conversion_rate:{label:'INR UPI Rate',desc:'ADR required per ₹1',type:'number',unit:'ADR/₹'},max_pending_withdrawals:{label:'Max Pending Withdrawals',desc:'Pending requests allowed per user',type:'number'},max_daily_withdrawals:{label:'Withdrawals per Day',desc:'Maximum payout requests per user per day',type:'number'},
 leaderboard_refresh_seconds:{label:'Leaderboard Refresh',desc:'Refresh interval',type:'number',unit:'sec'},leaderboard_max_entries:{label:'Leaderboard Rows',desc:'Maximum entries',type:'number'},contest_max_winners:{label:'Contest Max Winners',desc:'Maximum supported winners',type:'number'},promo_default_reward:{label:'Default Promo Reward',desc:'Default promo ADR reward',type:'number',unit:'ADR'},promo_default_max_claims:{label:'Default Promo Claims',desc:'Default claim cap',type:'number'},maintenance_mode:{label:'Maintenance Mode',desc:'Disable normal app use while admins keep access',type:'toggle'},bot_name:{label:'Bot Name',desc:'Public app/bot display name',type:'text'},app_version:{label:'App Version',desc:'Displayed app version',type:'text'},support_username:{label:'Support Username',desc:'Telegram support username',type:'text'},channel_username:{label:'Channel Username',desc:'Main Telegram channel',type:'text'},
};
const CSS=`.as-root{color:inherit}.as-live{display:flex;gap:9px;align-items:center;padding:11px 12px;border-radius:15px;background:rgba(34,197,94,.08);border:1px solid rgba(34,197,94,.2);font-size:11px;color:#86efac;margin-bottom:11px}.as-live svg{width:16px}.as-search{position:relative;margin-bottom:11px}.as-search svg{position:absolute;left:12px;top:50%;transform:translateY(-50%);width:15px;opacity:.4}.as-search input{width:100%;padding:12px 12px 12px 36px;border-radius:14px;color:inherit}.as-group{border-radius:18px;background:linear-gradient(145deg,rgba(255,255,255,.08),rgba(255,255,255,.025)),rgba(10,15,27,.42);border:1px solid rgba(255,255,255,.08);overflow:hidden;margin-bottom:9px}.as-gh{width:100%;display:flex;align-items:center;gap:10px;padding:13px;border:0;background:transparent;color:inherit;text-align:left}.as-gicon{width:34px;height:34px;border-radius:11px;display:grid;place-items:center;background:rgba(255,216,77,.08);color:#ffd84d}.as-gicon svg{width:16px}.as-gtitle{font-weight:800;flex:1}.as-count{font-size:9px;opacity:.4}.as-list{padding:0 9px 9px}.as-row{padding:11px;border-radius:13px;background:rgba(0,0,0,.17);border:1px solid rgba(255,255,255,.06);margin-top:7px}.as-head{display:flex;justify-content:space-between;gap:8px}.as-label{font-size:12px;font-weight:800}.as-desc{font-size:9px;opacity:.42;margin-top:2px}.as-db{font-size:8px;color:#4ade80;white-space:nowrap}.as-edit{display:flex;gap:7px;margin-top:9px}.as-input{flex:1;min-width:0;padding:10px;border-radius:10px;color:inherit}.as-save{border:0;border-radius:10px;padding:0 12px;background:#ffd84d;color:#171006;font-weight:900}.as-toggle{width:100%;padding:10px;border-radius:11px;border:1px solid;margin-top:9px;font-weight:850}.as-toggle.on{background:rgba(34,197,94,.1);border-color:rgba(34,197,94,.25);color:#4ade80}.as-toggle.off{background:rgba(239,68,68,.08);border-color:rgba(239,68,68,.2);color:#f87171}.as-unit,.as-status{font-size:8px;opacity:.45;margin-top:5px}.as-status.ok{color:#4ade80;opacity:1}.as-status.err{color:#f87171;opacity:1}[data-theme='light'] .as-group{background:rgba(255,255,255,.88);border-color:rgba(15,23,42,.08);box-shadow:0 10px 25px rgba(50,65,90,.06)}[data-theme='light'] .as-row{background:rgba(248,250,252,.8);border-color:rgba(15,23,42,.07)}[data-theme='light'] .as-input{color:#0f172a}`;
function groupIcon(title:string){if(title==='Withdrawals & Rates')return WalletCards;if(title==='System')return ShieldCheck;if(title.includes('Promo'))return BadgeDollarSign;if(title.includes('Users'))return IndianRupee;return Database}
export default function AdminSettingsTab({settings,editSettings,setEditSettings}:Props){const[live,setLive]=useState(settings);const[q,setQ]=useState('');const[open,setOpen]=useState<Record<string,boolean>>({'Withdrawals & Rates':true,'Ads — Shared':true,Adsgram:true,Monetag:true,GigaPub:true});const[savingKey,setSavingKey]=useState<string|null>(null);const[status,setStatus]=useState<Record<string,string>>({});useEffect(()=>{setLive(settings);setEditSettings(settings)},[settings,setEditSettings]);const groups=useMemo(()=>GROUPS.map(([title,keys])=>({title,keys:keys.filter(k=>{const m=M[k];return !q||(m.label+' '+m.desc+' '+k).toLowerCase().includes(q.toLowerCase())})})).filter(g=>g.keys.length),[q]);const save=async(k:string,v?:string)=>{const value=String(v??editSettings[k]??'').trim();setSavingKey(k);setStatus(p=>({...p,[k]:'Saving…'}));const r=await adminUpdateSetting(k,value);if(r.success&&r.data){setLive(p=>({...p,[k]:r.data!.value}));setEditSettings(p=>({...p,[k]:r.data!.value}));setStatus(p=>({...p,[k]:'Saved ✓'}))}else setStatus(p=>({...p,[k]:r.message||'Save failed'}));setSavingKey(null)};return <div className="as-root"><style>{CSS}</style><div className="as-live"><Database/>Backend V2 live settings — every save is confirmed from the database.</div><div className="as-search"><Search/><input placeholder="Search settings…" value={q} onChange={e=>setQ(e.target.value)}/></div>{groups.map(g=>{const Icon=groupIcon(g.title);return <div className="as-group" key={g.title}><button className="as-gh" onClick={()=>setOpen(p=>({...p,[g.title]:!p[g.title]}))}><span className="as-gicon"><Icon/></span><span className="as-gtitle">{g.title}</span><span className="as-count">{g.keys.length}</span>{open[g.title]?<ChevronUp size={15}/>:<ChevronDown size={15}/>}</button>{open[g.title]&&<div className="as-list">{g.keys.map(k=>{const m=M[k],v=String(editSettings[k]??live[k]??''),db=String(live[k]??''),changed=v!==db,onv=!['false','0','off','no',''].includes(v.toLowerCase());return <div className="as-row" key={k}><div className="as-head"><div><div className="as-label">{m.label}</div><div className="as-desc">{m.desc}</div></div><div className="as-db">DB: {db||'—'}</div></div>{m.type==='toggle'?<button disabled={savingKey===k} className={`as-toggle ${onv?'on':'off'}`} onClick={()=>{const nv=onv?'false':'true';setEditSettings(p=>({...p,[k]:nv}));void save(k,nv)}}>{onv?'ENABLED':'DISABLED'}</button>:<div className="as-edit"><input className="as-input" type={m.type==='number'?'number':'text'} value={v} onChange={e=>setEditSettings(p=>({...p,[k]:e.target.value}))} onKeyDown={e=>{if(e.key==='Enter')void save(k)}}/><button className="as-save" disabled={!changed||savingKey===k} onClick={()=>void save(k)}>{savingKey===k?'…':'SAVE'}</button></div>}{m.unit&&<div className="as-unit">Unit: {m.unit}</div>}{status[k]&&<div className={`as-status ${status[k].includes('✓')?'ok':status[k].toLowerCase().includes('fail')?'err':''}`}>{status[k]}</div>}</div>})}</div>}</div>})}</div>}
