import React, { useMemo, useState } from 'react';

interface WithdrawalItem {
  id: string; public_id?: string; method: string; points_spent: number; amount: number; fee?: number;
  status: string; wallet_address: string | null; created_at: string; processed_at?: string | null;
  admin_note: string | null; rejection_reason?: string | null; txid?: string | null; payment_reference?: string | null;
  processed_by?: number | null; processed_by_name?: string | null;
  users: { first_name: string; last_name?: string | null; username: string; telegram_id: number; photo_url: string | null } | null;
}
interface Props { withdrawals: WithdrawalItem[]; onApprove?: (id:string)=>void; onReject?: (id:string)=>void; }
type Delivery={chatId?:number;status:string;messageId?:number;error?:string;skipped?:boolean};

const URL='https://eoppaqrqlpyqoizohoba.supabase.co/functions/v1/admin-withdrawal';
const KEY='sb_publishable_DJ7o0hTt3DPL8O_3HbAWuw_NkdvY0na';
const reasons=['Invalid wallet/UPI','Fraud or abuse detected','Multiple accounts','Withdrawal requirements not met','Incorrect payment details','Suspicious activity','Other'];
function initData(){return (window as any).Telegram?.WebApp?.initData||''}
async function action(body:Record<string,unknown>){const r=await fetch(URL,{method:'POST',headers:{'Content-Type':'application/json','apikey':KEY,'x-telegram-init-data':initData()},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||'Request failed');return d}
const method=(m:string)=>m==='usdt_polygon'?'USDT · Polygon':m==='ton'?'GRAM · TON':m==='upi'?'INR · UPI':m;
const amount=(w:WithdrawalItem)=>w.method==='upi'?`₹${Number(w.amount).toFixed(2)}`:w.method==='usdt_polygon'?`$${Number(w.amount).toFixed(4)}`:`${Number(w.amount).toFixed(6)} TON`;
const styles=`
.wa{color:#fff}.wa-top{display:grid;grid-template-columns:repeat(4,1fr);gap:7px;margin-bottom:14px}.wa-stat,.wa-card{background:#ffffff08;border:1px solid #ffffff12;border-radius:15px}.wa-stat{padding:11px;text-align:center}.wa-stat b{display:block;font-size:20px}.wa-stat span{font-size:9px;color:#ffffff66}.wa-card{padding:14px;margin-bottom:10px}.wa-row{display:flex;justify-content:space-between;gap:10px;align-items:flex-start}.wa-name{font-weight:800}.wa-sub{font-size:11px;color:#ffffff70;margin-top:3px}.wa-status{font-size:9px;font-weight:900;letter-spacing:1px;padding:5px 8px;border-radius:999px;background:#ffffff10}.wa-data{margin-top:11px;padding:10px;border-radius:11px;background:#00000030;font-size:12px;line-height:1.65;word-break:break-word}.wa-actions{display:flex;gap:7px;margin-top:10px;flex-wrap:wrap}.wa-btn{border:0;border-radius:11px;padding:10px 12px;font-weight:800;color:#fff;background:#ffffff12}.wa-green{background:#16a34a}.wa-blue{background:#2563eb}.wa-red{background:#991b1b}.wa-input,.wa-select{width:100%;box-sizing:border-box;margin-top:8px;border-radius:10px;padding:10px;background:#090d17;border:1px solid #ffffff20;color:#fff}.wa-box{margin-top:10px;padding:10px;border-radius:11px;border:1px solid #ffffff14;background:#ffffff05}.wa-del{font-size:11px;margin-top:5px}.wa-ok{color:#86efac}.wa-bad{color:#fca5a5}.wa-muted{color:#ffffff55;font-size:11px}.wa-final{margin-top:8px;font-size:11px;color:#fca5a5}.wa-filter{display:flex;gap:6px;overflow:auto;margin-bottom:12px}.wa-filter button{border:1px solid #ffffff15;background:#ffffff08;color:#ffffffaa;padding:7px 10px;border-radius:999px}.wa-filter button.on{background:#ffffff18;color:#fff}
`;
export default function AdminWithdrawalsTab({withdrawals}:Props){
 const [rows,setRows]=useState(withdrawals);const [filter,setFilter]=useState('all');const [busy,setBusy]=useState<string|null>(null);const [error,setError]=useState('');const [deliveries,setDeliveries]=useState<Record<string,Delivery[]>>({});
 const [rejecting,setRejecting]=useState<string|null>(null);const [reason,setReason]=useState(reasons[0]);const [customReason,setCustomReason]=useState('');
 const [paying,setPaying]=useState<string|null>(null);const [reference,setReference]=useState('');const [fee,setFee]=useState('0');
 const counts=useMemo(()=>({pending:rows.filter(x=>x.status==='pending').length,approved:rows.filter(x=>x.status==='approved').length,paid:rows.filter(x=>x.status==='paid').length,rejected:rows.filter(x=>x.status==='rejected').length}),[rows]);
 const list=filter==='all'?rows:rows.filter(x=>x.status===filter);
 async function run(id:string,kind:string,payload:Record<string,unknown>={}){setBusy(id);setError('');try{const d=await action({withdrawalId:id,action:kind,...payload});if(d.deliveries)setDeliveries(v=>({...v,[id]:d.deliveries}));setRows(v=>v.map(w=>w.id===id?{...w,status:d.status||w.status,rejection_reason:kind==='rejected'?String(payload.rejectionReason||''):w.rejection_reason,txid:kind==='paid'&&w.method!=='upi'?String(payload.txid||''):w.txid,payment_reference:kind==='paid'&&w.method==='upi'?String(payload.paymentReference||''):w.payment_reference,fee:kind==='paid'?Number(payload.fee||0):w.fee,processed_at:['paid','rejected'].includes(kind)?new Date().toISOString():w.processed_at}:w));setRejecting(null);setPaying(null);setReference('');setFee('0')}catch(e){setError((e as Error).message)}finally{setBusy(null)}}
 return <div className="wa"><style>{styles}</style>
  <div className="wa-top"><div className="wa-stat"><b>{counts.pending}</b><span>PENDING</span></div><div className="wa-stat"><b>{counts.approved}</b><span>APPROVED</span></div><div className="wa-stat"><b>{counts.paid}</b><span>PAID</span></div><div className="wa-stat"><b>{counts.rejected}</b><span>REJECTED</span></div></div>
  <div className="wa-filter">{['all','pending','approved','paid','rejected'].map(x=><button key={x} className={filter===x?'on':''} onClick={()=>setFilter(x)}>{x.toUpperCase()}</button>)}</div>
  {error&&<div className="wa-box wa-bad">{error}</div>}
  {list.map(w=>{const u=w.users,name=[u?.first_name,u?.last_name].filter(Boolean).join(' ')||'User';return <div className="wa-card" key={w.id}>
   <div className="wa-row"><div><div className="wa-name">{name} {u?.username&&<span className="wa-muted">@{u.username}</span>}</div><div className="wa-sub">{w.public_id||w.id} · UID {u?.telegram_id}</div></div><div className="wa-status">{w.status.toUpperCase()}</div></div>
   <div className="wa-data"><b>{Number(w.points_spent).toLocaleString()} ADR</b> → <b>{amount(w)}</b><br/>Method: {method(w.method)}<br/>{w.method==='upi'?'UPI ID':'Wallet'}: {w.wallet_address||'—'}<br/>Requested: {new Date(w.created_at).toLocaleString('en-IN')}{w.txid&&<><br/>TXID: {w.txid}</>}{w.payment_reference&&<><br/>UTR/Reference: {w.payment_reference}</>}{w.rejection_reason&&<><br/>Reason: {w.rejection_reason}</>}</div>
   {w.status==='pending'&&<div className="wa-actions"><button className="wa-btn wa-green" disabled={busy===w.id} onClick={()=>run(w.id,'approved')}>✓ Approve</button><button className="wa-btn wa-red" disabled={busy===w.id} onClick={()=>setRejecting(w.id)}>✕ Reject</button></div>}
   {rejecting===w.id&&<div className="wa-box"><b>Reject withdrawal</b><select className="wa-select" value={reason} onChange={e=>setReason(e.target.value)}>{reasons.map(x=><option key={x}>{x}</option>)}</select>{reason==='Other'&&<input className="wa-input" placeholder="Custom rejection reason" value={customReason} onChange={e=>setCustomReason(e.target.value)}/>}<div className="wa-final">ADR will NOT be refunded. This action is final.</div><div className="wa-actions"><button className="wa-btn wa-red" disabled={busy===w.id||!(reason==='Other'?customReason.trim():reason)} onClick={()=>run(w.id,'rejected',{rejectionReason:reason==='Other'?customReason.trim():reason})}>Confirm Reject</button><button className="wa-btn" onClick={()=>setRejecting(null)}>Cancel</button></div></div>}
   {w.status==='approved'&&<><div className="wa-actions"><button className="wa-btn wa-blue" onClick={()=>setPaying(w.id)}>Enter Payment & Mark Paid</button></div>{paying===w.id&&<div className="wa-box"><b>{w.method==='upi'?'Payment Reference / UTR':'Transaction ID (TXID)'}</b><input className="wa-input" value={reference} onChange={e=>setReference(e.target.value)} placeholder={w.method==='upi'?'UTR / bank reference':'Blockchain TXID'}/><input className="wa-input" inputMode="decimal" value={fee} onChange={e=>setFee(e.target.value)} placeholder="Fee"/><div className="wa-actions"><button className="wa-btn wa-green" disabled={busy===w.id||!reference.trim()} onClick={()=>run(w.id,'paid',w.method==='upi'?{paymentReference:reference.trim(),fee:Number(fee||0)}:{txid:reference.trim(),fee:Number(fee||0)})}>Confirm Paid</button><button className="wa-btn" onClick={()=>setPaying(null)}>Cancel</button></div></div>}</>}
   {['paid','rejected'].includes(w.status)&&<><div className="wa-final">Final & immutable · normal admin actions cannot change this withdrawal.</div><div className="wa-actions"><button className="wa-btn" disabled={busy===w.id} onClick={()=>run(w.id,'retry-log')}>↻ Retry Log</button></div></>}
   {deliveries[w.id]?.length>0&&<div className="wa-box"><b>Telegram delivery</b>{deliveries[w.id].map((d,i)=><div key={i} className={`wa-del ${d.status==='sent'?'wa-ok':'wa-bad'}`}>{d.status==='sent'?'✓':'✕'} {d.chatId||'@Adr_pay'} · {d.status}{d.skipped?' (already sent)':''}{d.error?` · ${d.error}`:''}</div>)}</div>}
  </div>})}
  {!list.length&&<div className="wa-muted">No withdrawals in this filter.</div>}
 </div>;
}
