import React, { useEffect, useMemo, useState } from 'react';
import { adminUpdateSetting } from '@/lib/api';

interface Props {
  settings: Record<string,string>;
  editSettings: Record<string,string>;
  setEditSettings: React.Dispatch<React.SetStateAction<Record<string,string>>>;
  onSave: (key:string)=>void;
  saving: string|null;
}

type Meta={label:string;desc:string;type:'number'|'text'|'toggle';unit?:string};
const GROUPS=[
  ['🎬','Ads',['ad_reward_points','ad_cooldown_seconds','ad_init_delay_seconds','max_ads_per_hour','max_ads_per_day','adsgram_block_id']],
  ['👆','Tap & Energy',['tap_reward_points','tap_max_energy','tap_energy_regen_per_hour','tap_rate_limit_per_second','tap_x2_duration_seconds','tap_fast_regen_duration_seconds','tap_fast_regen_multiplier']],
  ['🌾','Farm',['farm_reward_points','farm_duration_minutes']],
  ['🎁','Daily Drop',['daily_drop_base','daily_drop_increment','daily_drop_max_days','daily_drop_cooldown_seconds']],
  ['🔥','Daily Reward',['daily_bonus_base','daily_bonus_streak_multiplier']],
  ['🎡','Spin Wheel',['max_daily_spins','spin_cooldown_hours','spin_reward_min','spin_reward_max','spin_jackpot','spin_jackpot_chance']],
  ['👥','Users & Referrals',['welcome_bonus','points_per_referral','referral_bonus_referred','max_referral_bonus']],
  ['🎮','Games',['game_daily_limit','tower_daily_limit','tower_max_reward','tower_reward_multiplier','dice_reward_enabled','cardflip_reward_enabled','numberguess_reward_enabled','luckybox_reward_enabled']],
  ['💸','Withdrawals & Rates',['withdrawal_enabled','min_withdrawal_points','max_pending_withdrawals','max_daily_withdrawals','required_daily_ads','stars_conversion_rate','usdt_conversion_rate','ton_conversion_rate']],
  ['🏆','Leaderboard & Contest',['leaderboard_refresh_seconds','leaderboard_max_entries','contest_max_winners']],
  ['🎟️','Promo Defaults',['promo_default_reward','promo_default_max_claims']],
  ['⚙️','System',['maintenance_mode','bot_name','app_version','support_username','channel_username']],
] as const;

const M:Record<string,Meta>={
 ad_reward_points:{label:'Reward per Ad',desc:'Real points paid after a verified ad',type:'number',unit:'pts'},
 ad_cooldown_seconds:{label:'Time per Ad',desc:'Minimum wait between rewarded ads',type:'number',unit:'sec'},
 ad_init_delay_seconds:{label:'First Ad Delay',desc:'Delay after app opens before ads can be used',type:'number',unit:'sec'},
 max_ads_per_hour:{label:'Ads per Hour',desc:'Rolling hourly rewarded-ad limit',type:'number'},max_ads_per_day:{label:'Ads per Day',desc:'Daily rewarded-ad limit',type:'number'},adsgram_block_id:{label:'Adsgram Block ID',desc:'Adsgram block identifier',type:'text'},
 tap_reward_points:{label:'Tap Reward',desc:'Base points per tap',type:'number',unit:'pts'},tap_max_energy:{label:'Max Energy',desc:'Maximum tap energy',type:'number'},tap_energy_regen_per_hour:{label:'Energy Regen',desc:'Energy regenerated each hour',type:'number',unit:'/hr'},tap_rate_limit_per_second:{label:'Tap Rate Limit',desc:'Accepted taps per second',type:'number',unit:'/sec'},tap_x2_duration_seconds:{label:'x2 Duration',desc:'Tap x2 boost duration',type:'number',unit:'sec'},tap_fast_regen_duration_seconds:{label:'Fast Regen Duration',desc:'Fast charge boost duration',type:'number',unit:'sec'},tap_fast_regen_multiplier:{label:'Fast Regen Multiplier',desc:'Fast energy regeneration multiplier',type:'number',unit:'x'},
 farm_reward_points:{label:'Farm Reward',desc:'Points credited per farm claim',type:'number',unit:'pts'},farm_duration_minutes:{label:'Farm Time',desc:'Minutes required before farm claim',type:'number',unit:'min'},
 daily_drop_base:{label:'Daily Drop Base',desc:'Day 1 Daily Drop reward',type:'number',unit:'pts'},daily_drop_increment:{label:'Daily Drop Increment',desc:'Extra reward for each streak day',type:'number',unit:'pts/day'},daily_drop_max_days:{label:'Daily Drop Max Days',desc:'Highest streak tier',type:'number',unit:'days'},daily_drop_cooldown_seconds:{label:'Drop Cooldown',desc:'Short claim UI cooldown',type:'number',unit:'sec'},
 daily_bonus_base:{label:'Daily Reward Base',desc:'Base Daily Reward amount',type:'number',unit:'pts'},daily_bonus_streak_multiplier:{label:'Daily Streak Bonus',desc:'Extra points per streak day',type:'number',unit:'pts/day'},
 max_daily_spins:{label:'Spins per Day',desc:'Maximum spin attempts per day',type:'number'},spin_cooldown_hours:{label:'Spin Reset',desc:'Spin cooldown/reset window',type:'number',unit:'hr'},spin_reward_min:{label:'Spin Min Reward',desc:'Minimum normal spin reward',type:'number',unit:'pts'},spin_reward_max:{label:'Spin Max Reward',desc:'Maximum normal spin reward',type:'number',unit:'pts'},spin_jackpot:{label:'Spin Jackpot',desc:'Jackpot reward',type:'number',unit:'pts'},spin_jackpot_chance:{label:'Jackpot Chance',desc:'Jackpot probability',type:'number',unit:'%'},
 welcome_bonus:{label:'Welcome Bonus',desc:'Points credited to a new user',type:'number',unit:'pts'},points_per_referral:{label:'Referrer Reward',desc:'Reward for a valid referral',type:'number',unit:'pts'},referral_bonus_referred:{label:'Referred User Bonus',desc:'Bonus for the new referred user',type:'number',unit:'pts'},max_referral_bonus:{label:'Max Referral Bonus',desc:'Maximum cumulative referral bonus',type:'number',unit:'pts'},
 game_daily_limit:{label:'Games per Day',desc:'Daily limit for standard games',type:'number'},tower_daily_limit:{label:'Tower Runs per Day',desc:'Daily Tower run limit',type:'number'},tower_max_reward:{label:'Tower Max Reward',desc:'Maximum Tower points per run',type:'number',unit:'pts'},tower_reward_multiplier:{label:'Tower Multiplier',desc:'Multiplier applied to Tower reward',type:'number',unit:'x'},dice_reward_enabled:{label:'Dice Rewards',desc:'Enable Dice reward payouts',type:'toggle'},cardflip_reward_enabled:{label:'Card Flip Rewards',desc:'Enable Card Flip payouts',type:'toggle'},numberguess_reward_enabled:{label:'Number Guess Rewards',desc:'Enable Number Guess payouts',type:'toggle'},luckybox_reward_enabled:{label:'Lucky Box Rewards',desc:'Enable Lucky Box payouts',type:'toggle'},
 withdrawal_enabled:{label:'Withdrawals Enabled',desc:'Master withdrawal switch',type:'toggle'},min_withdrawal_points:{label:'Minimum Withdrawal',desc:'Minimum points needed to withdraw',type:'number',unit:'pts'},max_pending_withdrawals:{label:'Max Pending Withdrawals',desc:'Maximum pending requests per user',type:'number'},max_daily_withdrawals:{label:'Withdrawals per Day',desc:'Maximum requests per day',type:'number'},required_daily_ads:{label:'Required Ads to Withdraw',desc:'Ads required today before withdrawal',type:'number'},stars_conversion_rate:{label:'Stars Rate',desc:'Points conversion rate for Telegram Stars',type:'number'},usdt_conversion_rate:{label:'USDT Rate',desc:'Points required per 1 USDT',type:'number',unit:'pts/$'},ton_conversion_rate:{label:'TON Rate',desc:'Points required per 1 TON',type:'number',unit:'pts/TON'},
 leaderboard_refresh_seconds:{label:'Leaderboard Refresh',desc:'Leaderboard refresh interval',type:'number',unit:'sec'},leaderboard_max_entries:{label:'Leaderboard Rows',desc:'Maximum leaderboard entries',type:'number'},contest_max_winners:{label:'Contest Max Winners',desc:'Maximum supported winners',type:'number'},promo_default_reward:{label:'Default Promo Reward',desc:'Default new promo reward',type:'number',unit:'pts'},promo_default_max_claims:{label:'Default Promo Claims',desc:'Default max promo claims',type:'number'},
 maintenance_mode:{label:'Maintenance Mode',desc:'Disable normal app usage',type:'toggle'},bot_name:{label:'Bot Name',desc:'Public app/bot display name',type:'text'},app_version:{label:'App Version',desc:'Displayed app version',type:'text'},support_username:{label:'Support Username',desc:'Telegram support username',type:'text'},channel_username:{label:'Channel Username',desc:'Main Telegram channel username',type:'text'},
};

const css=`.ls{color:#fff;font-family:system-ui,sans-serif}.ls-note{background:rgba(34,197,94,.08);border:1px solid rgba(34,197,94,.25);color:#86efac;padding:11px 13px;border-radius:13px;margin-bottom:12px;font-size:12px}.ls-search{width:100%;box-sizing:border-box;padding:12px 13px;background:#080b12;color:#fff;border:1px solid rgba(255,255,255,.1);border-radius:12px;outline:none;margin-bottom:11px}.ls-g{border:1px solid rgba(255,255,255,.07);background:rgba(255,255,255,.025);border-radius:16px;overflow:hidden;margin-bottom:9px}.ls-gh{width:100%;display:flex;gap:9px;align-items:center;background:none;border:0;color:#fff;padding:13px;text-align:left}.ls-title{font-weight:800;flex:1}.ls-count{font-size:10px;color:rgba(255,255,255,.35)}.ls-list{padding:0 9px 9px}.ls-r{padding:11px;border-radius:12px;border:1px solid rgba(255,255,255,.06);background:rgba(0,0,0,.2);margin-top:7px}.ls-head{display:flex;justify-content:space-between;gap:8px}.ls-label{font-size:13px;font-weight:800}.ls-desc{font-size:10px;color:rgba(255,255,255,.38);margin-top:2px}.ls-db{font-size:9px;color:#4ade80;white-space:nowrap}.ls-row{display:flex;gap:7px;margin-top:9px}.ls-in{flex:1;min-width:0;background:#060910;color:#fff;border:1px solid rgba(255,255,255,.1);border-radius:10px;padding:10px}.ls-save{border:0;border-radius:10px;padding:0 12px;background:#22c55e;color:#031108;font-weight:900}.ls-toggle{width:100%;padding:10px;border-radius:10px;border:1px solid rgba(255,255,255,.08);margin-top:9px;font-weight:900}.on{background:rgba(34,197,94,.12);color:#4ade80}.off{background:rgba(239,68,68,.1);color:#f87171}.changed{border-color:rgba(250,204,21,.35)}.ls-status{font-size:9px;margin-top:6px}.ok{color:#4ade80}.err{color:#f87171}.ls-unit{font-size:9px;color:rgba(255,255,255,.35);margin-top:5px}`;

export default function AdminSettingsTab({settings,editSettings,setEditSettings}:Props){
 const[live,setLive]=useState(settings);const[q,setQ]=useState('');const[open,setOpen]=useState<Record<string,boolean>>({Ads:true,'Tap & Energy':true,Farm:true,'Daily Drop':true});const[savingKey,setSavingKey]=useState<string|null>(null);const[status,setStatus]=useState<Record<string,string>>({});
 useEffect(()=>{setLive(settings);setEditSettings(settings)},[settings,setEditSettings]);
 const groups=useMemo(()=>GROUPS.map(([icon,title,keys])=>({icon,title,keys:keys.filter(k=>{const m=M[k];return !q||(m.label+' '+m.desc+' '+k).toLowerCase().includes(q.toLowerCase())})})).filter(g=>g.keys.length),[q]);
 const save=async(k:string,v?:string)=>{const value=String(v??editSettings[k]??'').trim();setSavingKey(k);setStatus(p=>({...p,[k]:'Saving…'}));const r=await adminUpdateSetting(k,value);if(r.success&&r.data){setLive(p=>({...p,[k]:r.data!.value}));setEditSettings(p=>({...p,[k]:r.data!.value}));setStatus(p=>({...p,[k]:'Saved to database ✓'}));}else setStatus(p=>({...p,[k]:r.message||'Save failed'}));setSavingKey(null)};
 return <div className="ls"><style>{css}</style><div className="ls-note">🟢 LIVE DATABASE SETTINGS — every save is written to Supabase and read back before confirmation.</div><input className="ls-search" placeholder="Search bot settings…" value={q} onChange={e=>setQ(e.target.value)}/>{groups.map(g=><div className="ls-g" key={g.title}><button className="ls-gh" onClick={()=>setOpen(p=>({...p,[g.title]:!p[g.title]}))}><span>{g.icon}</span><span className="ls-title">{g.title}</span><span className="ls-count">{g.keys.length} · {open[g.title]?'▲':'▼'}</span></button>{open[g.title]&&<div className="ls-list">{g.keys.map(k=>{const m=M[k],v=String(editSettings[k]??live[k]??''),db=String(live[k]??''),changed=v!==db,onv=!['false','0','off','no',''].includes(v.toLowerCase());return <div className={`ls-r ${changed?'changed':''}`} key={k}><div className="ls-head"><div><div className="ls-label">{m.label}</div><div className="ls-desc">{m.desc}</div></div><div className="ls-db">DB: {db||'—'}</div></div>{m.type==='toggle'?<button disabled={savingKey===k} className={`ls-toggle ${onv?'on':'off'}`} onClick={()=>{const nv=onv?'false':'true';setEditSettings(p=>({...p,[k]:nv}));void save(k,nv)}}>{onv?'ON ✓':'OFF ✕'}</button>:<div className="ls-row"><input className="ls-in" type={m.type==='number'?'number':'text'} value={v} onChange={e=>setEditSettings(p=>({...p,[k]:e.target.value}))} onBlur={()=>{if(changed)void save(k)}} onKeyDown={e=>{if(e.key==='Enter')(e.currentTarget as HTMLInputElement).blur()}}/><button className="ls-save" disabled={!changed||savingKey===k} onClick={()=>void save(k)}>{savingKey===k?'…':'SAVE'}</button></div>}{m.unit&&<div className="ls-unit">Unit: {m.unit}</div>}{status[k]&&<div className={`ls-status ${status[k].includes('✓')?'ok':status[k].includes('fail')?'err':''}`}>{status[k]}</div>}</div>})}</div>}</div>)}</div>
}
