import React from 'react';
import { useApp } from '@/context/AppContext';
import { usePreferences } from '@/context/PreferencesContext';

function triggerHaptic(type:'impact'|'success'='impact'){const tg=(window as any).Telegram?.WebApp;if(type==='success')tg?.HapticFeedback?.notificationOccurred('success');else tg?.HapticFeedback?.impactOccurred('light')}
const TYPE_CONFIG:Record<string,{icon:string;color:string;glow:string;key:string}>={info:{icon:'📢',color:'#22d3ee',glow:'rgba(34,211,238,.4)',key:'info'},reward:{icon:'🎁',color:'#ffbe00',glow:'rgba(255,190,0,.4)',key:'reward'},withdrawal:{icon:'💸',color:'#4ade80',glow:'rgba(74,222,128,.4)',key:'withdraw'},referral:{icon:'👥',color:'#a78bfa',glow:'rgba(167,139,250,.4)',key:'referral'}};
const DEFAULT_TYPE={icon:'🔔',color:'#94a3b8',glow:'rgba(148,163,184,.3)',key:'notifications'};
function timeAgo(date:string){const diff=Date.now()-new Date(date).getTime(),sec=Math.floor(diff/1000);if(sec<60)return '•';if(sec<3600)return `${Math.floor(sec/60)}m`;if(sec<86400)return `${Math.floor(sec/3600)}h`;return `${Math.floor(sec/86400)}d`}
function hexToRgb(hex:string){const h=hex.replace('#','');return `${parseInt(h.slice(0,2),16)},${parseInt(h.slice(2,4),16)},${parseInt(h.slice(4,6),16)}`}
const CSS=`
.np-root{font-family:'Rajdhani',sans-serif;padding:0 16px 112px;color:#fff;min-height:100vh}.np-header{display:flex;align-items:flex-start;justify-content:space-between;padding:4px 0 20px}.np-eyebrow{font:600 9px 'Orbitron',monospace;letter-spacing:4px;color:rgba(255,255,255,.2);text-transform:uppercase;margin-bottom:4px}.np-title{font:900 22px 'Orbitron',monospace;letter-spacing:2px;color:#fff}.np-title span{color:#22d3ee}.np-unread-badge{margin-top:4px;padding:5px 12px;border-radius:20px;background:rgba(255,190,0,.08);border:1px solid rgba(255,190,0,.25);font:700 9px 'Orbitron',monospace;color:#ffbe00}.np-empty{display:flex;flex-direction:column;align-items:center;padding:60px 0;text-align:center}.np-empty-icon{font-size:52px;margin-bottom:16px}.np-empty-title{font:700 13px 'Orbitron',monospace;letter-spacing:2px;opacity:.42;margin-bottom:6px}.np-empty-sub{font-size:12px;opacity:.18}.np-card{width:100%;text-align:left;border-radius:18px;padding:14px 16px;margin-bottom:8px;display:block;position:relative;overflow:hidden;color:inherit}.np-card-inner{display:flex;align-items:flex-start;gap:12px;position:relative;z-index:1}.np-icon-tile{width:44px;height:44px;border-radius:13px;display:grid;place-items:center;font-size:20px;flex-shrink:0}.np-card-body{flex:1;min-width:0}.np-card-top{display:flex;align-items:center;justify-content:space-between;gap:8px;margin-bottom:4px}.np-card-title{font-size:15px;font-weight:700;color:rgba(255,255,255,.9);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.np-card-title.read{opacity:.52}.np-type-tag{font:600 7px 'Orbitron',monospace;letter-spacing:1.5px;text-transform:uppercase;padding:2px 7px;border-radius:6px}.np-card-msg{font-size:12px;color:rgba(255,255,255,.35);line-height:1.5;margin-bottom:8px}.np-card-msg.unread{color:rgba(255,255,255,.62)}.np-card-footer{display:flex;align-items:center;justify-content:space-between}.np-time{font:600 8px 'Orbitron',monospace;opacity:.2}.np-unread-dot{width:8px;height:8px;border-radius:50%}.np-read-check{font-size:10px;opacity:.2}.np-divider{font:600 8px 'Orbitron',monospace;letter-spacing:2px;opacity:.18;text-transform:uppercase;margin:14px 0 8px 2px}[data-theme='light'] .np-root{color:#0f172a}[data-theme='light'] .np-title{color:#0f172a}[data-theme='light'] .np-eyebrow,[data-theme='light'] .np-empty-sub,[data-theme='light'] .np-divider{color:rgba(15,23,42,.45);opacity:1}[data-theme='light'] .np-card{background:rgba(255,255,255,.78)!important;border-color:rgba(15,23,42,.08)!important;box-shadow:0 10px 28px rgba(45,60,90,.07)!important}[data-theme='light'] .np-card-title{color:#172033}[data-theme='light'] .np-card-msg,[data-theme='light'] .np-card-msg.unread{color:rgba(15,23,42,.52)}
`;
export default function NotificationsPage(){const{notifications,markRead}=useApp();const{t}=usePreferences();const unread=notifications.filter(n=>!n.is_read),read=notifications.filter(n=>n.is_read);function renderCard(n:any){const tc=TYPE_CONFIG[n.type]||DEFAULT_TYPE;return <button key={n.id} className="np-card" onClick={()=>{triggerHaptic();if(!n.is_read){markRead(n.id);triggerHaptic('success')}}} style={{background:n.is_read?'rgba(255,255,255,.02)':`rgba(${hexToRgb(tc.color)},.05)`,border:`1px solid ${n.is_read?'rgba(255,255,255,.05)':`${tc.color}35`}`}}><div className="np-card-inner"><div className="np-icon-tile" style={{background:`${tc.color}${n.is_read?'08':'12'}`,border:`1px solid ${tc.color}${n.is_read?'15':'30'}`}}>{tc.icon}</div><div className="np-card-body"><div className="np-card-top"><div className={`np-card-title ${n.is_read?'read':''}`}>{n.title}</div><div className="np-type-tag" style={{background:`${tc.color}10`,border:`1px solid ${tc.color}25`,color:tc.color}}>{t(tc.key)}</div></div><div className={`np-card-msg ${n.is_read?'':'unread'}`}>{n.message}</div><div className="np-card-footer"><div className="np-time">{timeAgo(n.created_at)}</div>{!n.is_read?<div className="np-unread-dot" style={{background:tc.color}}/>:<div className="np-read-check">✓</div>}</div></div></div></button>}
return <><style>{CSS}</style><div className="np-root"><div className="np-header"><div><div className="np-eyebrow">{t('notifications')}</div><div className="np-title">{t('notifications').toUpperCase()}</div></div>{unread.length>0&&<div className="np-unread-badge">● {unread.length} NEW</div>}</div>{notifications.length===0&&<div className="np-empty"><div className="np-empty-icon">🔔</div><div className="np-empty-title">{t('notifications')}</div><div className="np-empty-sub">{t('noNotifications')}</div></div>}{unread.length>0&&<><div className="np-divider">✦ {t('new')} · {unread.length}</div>{unread.map(renderCard)}</>}{read.length>0&&<><div className="np-divider">{t('history')}</div>{read.map(renderCard)}</>}</div></>}
