import React from 'react';
import { BookOpen, Check, Languages, Moon, Sun, X } from 'lucide-react';
import { LANGUAGES, usePreferences } from '@/context/PreferencesContext';

const CSS=`
.as-overlay{position:fixed;inset:0;z-index:300;background:rgba(2,5,12,.58);backdrop-filter:blur(14px);-webkit-backdrop-filter:blur(14px);display:flex;align-items:flex-end;justify-content:center;padding:12px}.as-sheet{width:100%;max-width:470px;max-height:86vh;overflow:auto;border-radius:28px;padding:16px;background:linear-gradient(145deg,rgba(255,255,255,.15),rgba(255,255,255,.045)),rgba(9,14,25,.9);border:1px solid rgba(255,255,255,.16);box-shadow:inset 0 1px 0 rgba(255,255,255,.2),0 30px 80px rgba(0,0,0,.5);backdrop-filter:blur(32px) saturate(165%);-webkit-backdrop-filter:blur(32px) saturate(165%)}
.as-head{display:flex;align-items:center;gap:10px;margin-bottom:14px}.as-icon{width:40px;height:40px;border-radius:14px;display:grid;place-items:center;background:rgba(255,255,255,.08);border:1px solid rgba(255,255,255,.12)}.as-icon svg{width:19px}.as-title{flex:1;font:800 15px 'Orbitron',sans-serif}.as-close{border:0;background:rgba(255,255,255,.07);color:inherit;width:36px;height:36px;border-radius:13px;display:grid;place-items:center}.as-close svg{width:17px}.as-section{margin-top:14px}.as-label{font-size:10px;font-weight:800;letter-spacing:1.6px;text-transform:uppercase;opacity:.46;margin:0 2px 8px}.as-theme{display:grid;grid-template-columns:1fr 1fr;gap:8px}.as-theme button,.as-guide{border-radius:16px;border:1px solid rgba(255,255,255,.1);background:rgba(255,255,255,.05);color:inherit;padding:13px;display:flex;align-items:center;justify-content:center;gap:8px;font-weight:700}.as-theme button.active{border-color:rgba(255,205,80,.38);background:rgba(255,190,0,.11);color:#ffe493}.as-theme svg,.as-guide svg{width:18px}.as-langs{display:grid;grid-template-columns:1fr 1fr;gap:7px}.as-lang{border:1px solid rgba(255,255,255,.085);background:rgba(255,255,255,.035);color:inherit;border-radius:15px;padding:10px 11px;display:flex;align-items:center;gap:8px;text-align:left}.as-lang.active{border-color:rgba(99,202,255,.35);background:rgba(34,211,238,.08)}.as-lang-flag{font-size:18px}.as-lang-name{flex:1;font-size:12px;font-weight:650}.as-lang svg{width:14px;color:#4ade80}.as-guide{width:100%;justify-content:flex-start;background:linear-gradient(145deg,rgba(255,214,92,.14),rgba(255,190,0,.055));border-color:rgba(255,215,100,.2);color:#ffe28a}.as-guide small{display:block;color:rgba(255,255,255,.38);font-weight:500;margin-top:2px}
[data-theme='light'] .as-overlay{background:rgba(210,220,238,.5)}[data-theme='light'] .as-sheet{background:linear-gradient(145deg,rgba(255,255,255,.96),rgba(243,247,255,.9));color:#0f172a;border-color:rgba(15,23,42,.08);box-shadow:0 28px 70px rgba(40,55,85,.2)}[data-theme='light'] .as-theme button,[data-theme='light'] .as-lang,[data-theme='light'] .as-close{background:rgba(15,23,42,.04);border-color:rgba(15,23,42,.08)}
`;

export default function AppSettingsSheet({open,onClose}:{open:boolean;onClose:()=>void}){
  const {language,setLanguage,theme,setTheme,t}=usePreferences();
  if(!open)return null;
  const openGuide=()=>{window.dispatchEvent(new CustomEvent('app:navigate',{detail:'guide'}));onClose();};
  return <><style>{CSS}</style><div className="as-overlay" onClick={e=>{if(e.target===e.currentTarget)onClose();}}><div className="as-sheet">
    <div className="as-head"><div className="as-icon"><Languages/></div><div className="as-title">{t('settings')}</div><button className="as-close" onClick={onClose}><X/></button></div>
    <button className="as-guide" onClick={openGuide}><BookOpen/><span>{t('guide')}<small>Ads · Farm · Drop · Tasks · Referrals · Games · Promo · Withdraw</small></span></button>
    <div className="as-section"><div className="as-label">{t('theme')}</div><div className="as-theme"><button className={theme==='dark'?'active':''} onClick={()=>setTheme('dark')}><Moon/>{t('dark')}</button><button className={theme==='light'?'active':''} onClick={()=>setTheme('light')}><Sun/>{t('light')}</button></div></div>
    <div className="as-section"><div className="as-label">{t('language')}</div><div className="as-langs">{LANGUAGES.map(l=><button key={l.code} className={`as-lang ${language===l.code?'active':''}`} onClick={()=>setLanguage(l.code)}><span className="as-lang-flag">{l.flag}</span><span className="as-lang-name">{l.label}</span>{language===l.code&&<Check/>}</button>)}</div></div>
  </div></div></>;
}
