import React,{useEffect}from'react';
import {useApp}from'@/context/AppContext';
import{usePreferences}from'@/context/PreferencesContext';
import{Home,ListChecks,UsersRound,Trophy,WalletCards,Bell,Settings}from'lucide-react';

type Page='home'|'tasks'|'spin'|'referral'|'leaderboard'|'wallet'|'notifications'|'admin';
interface BottomNavProps{currentPage:Page;onNavigate:(page:Page)=>void;}
const CSS=`.bn-safe{position:fixed;left:10px;right:10px;bottom:max(10px,env(safe-area-inset-bottom,10px));z-index:100;pointer-events:none}.bn-bar{max-width:460px;margin:0 auto;min-height:67px;display:flex;align-items:center;justify-content:space-between;padding:7px;border-radius:24px;pointer-events:auto;background:linear-gradient(145deg,rgba(255,255,255,.115),rgba(255,255,255,.035)),rgba(8,12,22,.68);border:1px solid rgba(255,255,255,.14);box-shadow:inset 0 1px 0 rgba(255,255,255,.17),0 20px 48px rgba(0,0,0,.42);backdrop-filter:blur(30px) saturate(160%);-webkit-backdrop-filter:blur(30px) saturate(160%)}.bn-item{position:relative;flex:1;min-width:0;max-width:64px;min-height:51px;padding:7px 3px 5px;border:0;border-radius:17px;background:transparent;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:4px;color:rgba(226,232,240,.48);transition:.18s}.bn-item:active{transform:scale(.92)}.bn-item.active{color:#fff;background:linear-gradient(145deg,rgba(255,255,255,.15),rgba(255,190,0,.075));box-shadow:inset 0 1px 0 rgba(255,255,255,.18),0 8px 20px rgba(0,0,0,.19)}.bn-icon{width:20px;height:20px;stroke-width:1.8}.bn-item.active .bn-icon{color:#ffd45c;transform:translateY(-1px) scale(1.08);filter:drop-shadow(0 0 7px rgba(255,190,0,.38))}.bn-label{width:100%;font-family:'Inter',sans-serif;font-size:8px;line-height:1;font-weight:650;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;text-align:center}.bn-pip{position:absolute;bottom:1px;width:4px;height:4px;border-radius:99px;background:transparent}.bn-item.active .bn-pip{width:13px;background:#ffd45c;box-shadow:0 0 9px rgba(255,190,0,.65)}.bn-badge{position:absolute;top:3px;right:4px;min-width:16px;height:16px;padding:0 4px;border-radius:99px;background:linear-gradient(145deg,#fb7185,#e11d48);border:1px solid rgba(255,255,255,.28);display:grid;place-items:center;color:#fff;font-size:8px;font-weight:700}[data-theme='light'] .bn-bar{background:rgba(255,255,255,.9);border-color:rgba(15,23,42,.08);box-shadow:0 18px 40px rgba(50,65,90,.15)}[data-theme='light'] .bn-item{color:rgba(15,23,42,.5)}[data-theme='light'] .bn-item.active{color:#0f172a;background:rgba(255,190,0,.12)}`;
const DEEP_LINKS:Record<string,Page>={home:'home',tasks:'tasks',task:'tasks',refer:'referral',referral:'referral',invite:'referral',leaderboard:'leaderboard',rankings:'leaderboard',wallet:'wallet',withdraw:'wallet',alerts:'notifications',notifications:'notifications',admin:'admin'};
export default function BottomNav({currentPage,onNavigate}:BottomNavProps){const{isAdmin,unreadCount}=useApp();const{t}=usePreferences();useEffect(()=>{const raw=new URLSearchParams(window.location.search).get('page')?.toLowerCase().trim();const target=raw?DEEP_LINKS[raw]:undefined;if(target&&target!==currentPage&&(target!=='admin'||isAdmin))onNavigate(target);},[isAdmin,onNavigate]);const items=[['home',Home,t('home')],['tasks',ListChecks,t('tasks')],['referral',UsersRound,t('refer')],['leaderboard',Trophy,t('leaderboard')],['wallet',WalletCards,t('wallet')]]as const;const render=(id:Page,label:string,Icon:React.ComponentType<{className?:string}>,badge?:number)=><button key={id} className={`bn-item ${currentPage===id?'active':''}`} onClick={()=>onNavigate(id)} aria-label={label}><Icon className="bn-icon"/>{badge?<div className="bn-badge">{badge>9?'9+':badge}</div>:null}<span className="bn-label">{label}</span><div className="bn-pip"/></button>;return <><style>{CSS}</style><div className="bn-safe"><div className="bn-bar">{items.map(([id,Icon,label])=>render(id as Page,label,Icon))}{render('notifications',t('alerts'),Bell,unreadCount)}{isAdmin&&render('admin',t('admin'),Settings)}</div></div><div style={{height:'calc(88px + env(safe-area-inset-bottom, 0px))',flexShrink:0}}/></>}
