// @ts-nocheck
import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.55.0";
const URL=Deno.env.get('SUPABASE_URL')||'',KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'',TOKEN=Deno.env.get('TELEGRAM_BOT_TOKEN')||Deno.env.get('BOT_TOKEN')||'';
const APP='https://t.me/Adsrewartsbot/app';
const sb=createClient(URL,KEY,{auth:{persistSession:false,autoRefreshToken:false}});
const json=(d:any,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{'Content-Type':'application/json'}});
const esc=(v:any)=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
const fmt=(n:any)=>Number(n||0).toLocaleString('en-US');
function same(a:string,b:string){if(!a||a.length!==b.length)return false;let x=0;for(let i=0;i<a.length;i++)x|=a.charCodeAt(i)^b.charCodeAt(i);return x===0}
async function secret(){const{data}=await sb.rpc('get_bot_internal_secret',{p_name:'adsreward_telegram_webhook_secret'});return String(data||'')}
async function tg(method:string,p:any){const r=await fetch(`https://api.telegram.org/bot${TOKEN}/${method}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)});const b=await r.json().catch(()=>({ok:false}));if(!r.ok||!b.ok)throw new Error(b.description||method);return b.result}
async function send(chat:number,text:string,rows:any[][]=[]){return tg('sendMessage',{chat_id:chat,text,parse_mode:'HTML',disable_web_page_preview:true,...(rows.length?{reply_markup:{inline_keyboard:rows}}:{})})}
async function getUser(m:any){let{data:u}=await sb.from('users').select('*').eq('telegram_id',Number(m.from.id)).maybeSingle();if(!u){const{data:r,error}=await sb.rpc('register_telegram_user',{p_telegram_id:Number(m.from.id),p_first_name:String(m.from.first_name||'User'),p_last_name:m.from.last_name||null,p_username:m.from.username||null,p_photo_url:null,p_referral_code:null});if(error)throw error;u=r?.user}return u}
async function invite(m:any,u:any){const{data:r}=await sb.from('referrals').select('is_verified,points_earned').eq('referrer_id',u.id);const all=r||[],valid=all.filter((x:any)=>x.is_verified),earned=all.reduce((a:any,x:any)=>a+Number(x.points_earned||0),0);const referral=`${APP}?startapp=${u.telegram_id}`;const share=`https://t.me/share/url?url=${encodeURIComponent(referral)}&text=${encodeURIComponent('Join AdsReward and earn ADR')}`;await send(m.chat.id,`👥 <b>Referrals</b>\n\nInvited: <b>${all.length}</b>\nQualified: <b>${valid.length}</b>\nEarned: <b>${fmt(earned)} ADR</b>\n\n<code>${esc(referral)}</code>`,[[{text:'📤 Share Invite',url:share}],[{text:'👥 View Referrals',url:APP}]])}
async function task(m:any,u:any){const now=new Date().toISOString();const{data:t}=await sb.from('tasks').select('id,reward_points').eq('is_active',true).or(`expires_at.is.null,expires_at.gt.${now}`).limit(200);const{data:d}=await sb.from('user_tasks').select('task_id').eq('user_id',u.id);const done=new Set((d||[]).map((x:any)=>x.task_id)),ready=(t||[]).filter((x:any)=>!done.has(x.id)),reward=ready.reduce((a:any,x:any)=>a+Number(x.reward_points||0),0);await send(m.chat.id,ready.length?`🎯 <b>Tasks</b>\n\n<b>${ready.length}</b> available\nUp to <b>${fmt(reward)} ADR</b> ready to earn.`:'✅ <b>Tasks</b>\n\nNo new tasks right now.',[[{text:'🎯 Open Tasks',url:APP}]])}
Deno.serve(async(req:Request)=>{try{if(req.method==='GET')return json({success:true,service:'telegram-group-commands',version:'v3-group-app-url'});if(req.method!=='POST')return json({handled:false},405);if(!same(await secret(),req.headers.get('x-telegram-bot-api-secret-token')||''))return json({handled:false},401);const u=await req.json().catch(()=>({})),m=u.message;if(!m?.from||m.from.is_bot||!['group','supergroup'].includes(String(m.chat?.type))||!m.text)return json({handled:false});const cmd=String(m.text).trim().split(/\s+/)[0].split('@')[0].toLowerCase();if(!['/invite','/task'].includes(cmd))return json({handled:false});const user=await getUser(m);if(!user)return json({handled:true});if(cmd==='/invite')await invite(m,user);else await task(m,user);return json({handled:true})}catch(e){console.error('telegram-group-commands',e);return json({handled:false,error:String(e.message||e)},500)}});