// @ts-nocheck
import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.55.0";
const URL=Deno.env.get('SUPABASE_URL')||'',KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'',TOKEN=Deno.env.get('TELEGRAM_BOT_TOKEN')||Deno.env.get('BOT_TOKEN')||'';
const APP='https://t.me/Adsrewartsbot/app';
const sb=createClient(URL,KEY,{auth:{persistSession:false,autoRefreshToken:false}});
const json=(d:any,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{'Content-Type':'application/json'}});
const esc=(v:any)=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
const fmt=(n:any)=>Number(n||0).toLocaleString('en-US');
const app=(text='🚀 Open AdsReward')=>({text,url:APP});
function same(a:string,b:string){if(!a||a.length!==b.length)return false;let x=0;for(let i=0;i<a.length;i++)x|=a.charCodeAt(i)^b.charCodeAt(i);return x===0}
async function secret(){const{data}=await sb.rpc('get_bot_internal_secret',{p_name:'adsreward_telegram_webhook_secret'});return String(data||'')}
async function tg(method:string,p:any){const r=await fetch(`https://api.telegram.org/bot${TOKEN}/${method}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)});const b=await r.json().catch(()=>({ok:false}));if(!r.ok||!b.ok)throw new Error(b.description||method);return b.result}
async function send(chat:number,text:string,rows:any[][]=[]){return tg('sendMessage',{chat_id:chat,text,parse_mode:'HTML',disable_web_page_preview:true,...(rows.length?{reply_markup:{inline_keyboard:rows}}:{})})}
async function getUser(m:any){let{data:u}=await sb.from('users').select('*').eq('telegram_id',Number(m.from.id)).maybeSingle();if(!u){const{data:r,error}=await sb.rpc('register_telegram_user',{p_telegram_id:Number(m.from.id),p_first_name:String(m.from.first_name||'User'),p_last_name:m.from.last_name||null,p_username:m.from.username||null,p_photo_url:null,p_referral_code:null});if(error)throw error;u=r?.user}return u}
async function bal(uid:string){const{data}=await sb.from('balances').select('points,total_earned,total_withdrawn').eq('user_id',uid).maybeSingle();return data||{points:0,total_earned:0,total_withdrawn:0}}
async function start(m:any,u:any){const b=await bal(u.id),name=esc(u.first_name||m.from.first_name||'User');await send(m.chat.id,`👋 <b>Welcome, ${name}</b>\n\n💎 Balance: <b>${fmt(b.points)} ADR</b>\n\nEarn with ads, tasks, farming and referrals.`,[[app()]])}
async function balance(m:any,u:any){const b=await bal(u.id);const{data:w}=await sb.from('withdrawals').select('points_spent').eq('user_id',u.id).in('status',['pending','approved']);const pending=(w||[]).reduce((a:any,x:any)=>a+Number(x.points_spent||0),0);await send(m.chat.id,`💎 <b>Your Balance</b>\n\nAvailable: <b>${fmt(b.points)} ADR</b>\nEarned: ${fmt(b.total_earned)} ADR\nWithdrawn: ${fmt(b.total_withdrawn)} ADR${pending?`\nPending: ${fmt(pending)} ADR`:''}`,[[app('💳 Open Wallet')]])}
async function invite(m:any,u:any){const{data:r}=await sb.from('referrals').select('is_verified,points_earned').eq('referrer_id',u.id);const all=r||[],valid=all.filter((x:any)=>x.is_verified),earned=all.reduce((a:any,x:any)=>a+Number(x.points_earned||0),0);const referral=`${APP}?startapp=${u.telegram_id}`;const share=`https://t.me/share/url?url=${encodeURIComponent(referral)}&text=${encodeURIComponent('Join AdsReward and earn ADR')}`;await send(m.chat.id,`👥 <b>Referrals</b>\n\nInvited: <b>${all.length}</b>\nQualified: <b>${valid.length}</b>\nEarned: <b>${fmt(earned)} ADR</b>\n\n<code>${esc(referral)}</code>`,[[{text:'📤 Share Invite',url:share}],[app('👥 View Referrals')]])}
async function task(m:any,u:any){const now=new Date().toISOString();const{data:t}=await sb.from('tasks').select('id,reward_points').eq('is_active',true).or(`expires_at.is.null,expires_at.gt.${now}`).limit(200);const{data:d}=await sb.from('user_tasks').select('task_id').eq('user_id',u.id);const done=new Set((d||[]).map((x:any)=>x.task_id)),ready=(t||[]).filter((x:any)=>!done.has(x.id)),reward=ready.reduce((a:any,x:any)=>a+Number(x.reward_points||0),0);await send(m.chat.id,ready.length?`🎯 <b>Tasks</b>\n\n<b>${ready.length}</b> available\nUp to <b>${fmt(reward)} ADR</b> ready to earn.`:'✅ <b>Tasks</b>\n\nNo new tasks right now.',[[app('🎯 Open Tasks')]])}
async function leaderboard(m:any){const{data:b}=await sb.from('balances').select('user_id,points').order('points',{ascending:false}).limit(10),ids=(b||[]).map((x:any)=>x.user_id);const{data:us}=ids.length?await sb.from('users').select('id,username,first_name').in('id',ids):{data:[]};const map=new Map((us||[]).map((x:any)=>[x.id,x]));const lines=(b||[]).map((x:any,i:number)=>{const u:any=map.get(x.user_id),name=u?.username?'@'+u.username:u?.first_name||'User',med=i===0?'🥇':i===1?'🥈':i===2?'🥉':`${i+1}.`;return `${med} ${esc(name)} — <b>${fmt(x.points)} ADR</b>`});await send(m.chat.id,`🏆 <b>Leaderboard</b>\n\n${lines.join('\n')||'No rankings yet.'}`,[[app('🏆 Open Leaderboard')]])}
async function withdraw(m:any){const{data:s}=await sb.from('settings').select('key,value').in('key',['withdrawal_enabled','min_withdrawal_points','withdraw_ton_enabled','withdraw_usdt_polygon_enabled','withdraw_upi_enabled']);const set=Object.fromEntries((s||[]).map((x:any)=>[x.key,String(x.value)]));if(['false','0','off'].includes(String(set.withdrawal_enabled||'true').toLowerCase())){await send(m.chat.id,'⏸ <b>Withdrawals are temporarily disabled.</b>',[[app('💳 Open Wallet')]]);return}const methods=[!['false','0','off'].includes(String(set.withdraw_ton_enabled||'true').toLowerCase())?'GRAM · TON':'',!['false','0','off'].includes(String(set.withdraw_usdt_polygon_enabled||'true').toLowerCase())?'USDT · Polygon':'',!['false','0','off'].includes(String(set.withdraw_upi_enabled||'true').toLowerCase())?'INR · UPI':''].filter(Boolean);await send(m.chat.id,`💸 <b>Withdraw ADR</b>\n\nMinimum: <b>${fmt(set.min_withdrawal_points||5000)} ADR</b>\nMethods: ${methods.join(' · ')||'Unavailable'}`,[[app('💳 Open Wallet')]])}
async function profile(m:any,u:any){const b=await bal(u.id),name=[u.first_name,u.last_name].filter(Boolean).join(' ')||'User';await send(m.chat.id,`👤 <b>Profile</b>\n\n${esc(name)}${u.username?` · @${esc(u.username)}`:''}\nUID: <code>${u.telegram_id}</code>\nLevel: <b>${u.level||1}</b>\nBalance: <b>${fmt(b.points)} ADR</b>`,[[app('🏠 Open AdsReward')]])}
async function stats(m:any,u:any){const[{count:ads},{count:tasks},{count:refs},b]=await Promise.all([sb.from('ad_logs').select('id',{count:'exact',head:true}).eq('user_id',u.id),sb.from('user_tasks').select('id',{count:'exact',head:true}).eq('user_id',u.id),sb.from('referrals').select('id',{count:'exact',head:true}).eq('referrer_id',u.id).eq('is_verified',true),bal(u.id)]);await send(m.chat.id,`📊 <b>Your Stats</b>\n\n📺 Ads: <b>${fmt(ads)}</b>\n🎯 Tasks: <b>${fmt(tasks)}</b>\n👥 Referrals: <b>${fmt(refs)}</b>\n💎 Total earned: <b>${fmt(b.total_earned)} ADR</b>`,[[app()]])}
async function missions(m:any,u:any){const[{count:ads},{count:tasks}]=await Promise.all([sb.from('ad_logs').select('id',{count:'exact',head:true}).eq('user_id',u.id).gte('created_at',new Date(Date.now()-86400000).toISOString()),sb.from('user_tasks').select('id',{count:'exact',head:true}).eq('user_id',u.id).gte('completed_at',new Date(Date.now()-86400000).toISOString())]);await send(m.chat.id,`🎯 <b>Missions</b>\n\nToday\n📺 Ads: <b>${fmt(ads)}</b>\n🎯 Tasks: <b>${fmt(tasks)}</b>`,[[app()]])}
async function achievements(m:any,u:any){const{data:a}=await sb.from('user_achievements').select('achievement_key,reward_points').eq('user_id',u.id);await send(m.chat.id,`🏆 <b>Achievements</b>\n\nUnlocked: <b>${(a||[]).length}</b>${a?.length?`\nRewards earned: <b>${fmt(a.reduce((x:any,y:any)=>x+Number(y.reward_points||0),0))} ADR</b>`:''}`,[[app()]])}
async function support(m:any){const{data:s}=await sb.from('settings').select('key,value').in('key',['support_username','channel_username']);const set=Object.fromEntries((s||[]).map((x:any)=>[x.key,String(x.value)])),sup=String(set.support_username||'@im_poorman').replace(/^@/,''),ch=String(set.channel_username||'@adsrewards').replace(/^@/,'');await send(m.chat.id,'🛟 <b>Support</b>\n\nNeed help with your AdsReward account?',[[{text:'💬 Contact Support',url:`https://t.me/${sup}`},{text:'📢 Updates',url:`https://t.me/${ch}`}],[app('🚀 Open AdsReward')]])}
async function help(m:any){await send(m.chat.id,'🛟 <b>AdsReward Bot — Help</b>\n\n/start — Open AdsReward\n/balance — Check ADR balance\n/profile — View profile\n/task — View tasks\n/invite — Referral stats & link\n/leaderboard — Rankings\n/withdraw — Withdraw ADR\n/stats — Account stats\n/missions — Missions\n/achievements — Achievements\n/support — Support\n/tip — Tip ADR in groups\n/giveaway — Start giveaway',[[app()]])}
async function language(m:any){await send(m.chat.id,'🌐 <b>Language</b>\n\nOpen AdsReward to manage your language.',[[app()]])}
const CMDS=new Set(['/start','/help','/balance','/invite','/leaderboard','/task','/withdraw','/profile','/stats','/missions','/achievements','/language','/support']);
Deno.serve(async(req:Request)=>{try{if(req.method==='GET')return json({success:true,service:'telegram-group-commands',version:'v4-all-group-user-commands'});if(req.method!=='POST')return json({handled:false},405);if(!same(await secret(),req.headers.get('x-telegram-bot-api-secret-token')||''))return json({handled:false},401);const up=await req.json().catch(()=>({})),m=up.message;if(!m?.from||m.from.is_bot||!['group','supergroup'].includes(String(m.chat?.type))||!m.text)return json({handled:false});const cmd=String(m.text).trim().split(/\s+/)[0].split('@')[0].toLowerCase();if(!CMDS.has(cmd))return json({handled:false});const user=await getUser(m);if(!user)return json({handled:true});if(user.is_banned){await send(m.chat.id,'🚫 <b>Account restricted.</b>');return json({handled:true})}if(cmd==='/start')await start(m,user);else if(cmd==='/help')await help(m);else if(cmd==='/balance')await balance(m,user);else if(cmd==='/invite')await invite(m,user);else if(cmd==='/leaderboard')await leaderboard(m);else if(cmd==='/task')await task(m,user);else if(cmd==='/withdraw')await withdraw(m);else if(cmd==='/profile')await profile(m,user);else if(cmd==='/stats')await stats(m,user);else if(cmd==='/missions')await missions(m,user);else if(cmd==='/achievements')await achievements(m,user);else if(cmd==='/language')await language(m);else if(cmd==='/support')await support(m);return json({handled:true})}catch(e){console.error('telegram-group-commands',e);return json({handled:false,error:String(e.message||e)},500)}});