// @ts-nocheck
import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.55.0";
const URL=Deno.env.get('SUPABASE_URL')||'',KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'',TOKEN=Deno.env.get('TELEGRAM_BOT_TOKEN')||Deno.env.get('BOT_TOKEN')||'';
const sb=createClient(URL,KEY,{auth:{persistSession:false,autoRefreshToken:false}});
const json=(d:any,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{'Content-Type':'application/json'}});
const esc=(v:any)=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
const fmt=(n:any)=>Number(n||0).toLocaleString('en-US');
function same(a:string,b:string){if(!a||a.length!==b.length)return false;let x=0;for(let i=0;i<a.length;i++)x|=a.charCodeAt(i)^b.charCodeAt(i);return x===0}
async function secret(){const{data}=await sb.rpc('get_bot_internal_secret',{p_name:'adsreward_telegram_webhook_secret'});return String(data||'')}
async function tg(method:string,p:any){const r=await fetch(`https://api.telegram.org/bot${TOKEN}/${method}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)});const b=await r.json().catch(()=>({ok:false}));if(!r.ok||!b.ok)throw new Error(b.description||method);return b.result}
async function send(chat:number,text:string,rows:any[][]=[]){return tg('sendMessage',{chat_id:chat,text,parse_mode:'HTML',disable_web_page_preview:true,...(rows.length?{reply_markup:{inline_keyboard:rows}}:{})})}
async function getUser(tid:number){let{data:u}=await sb.from('users').select('*').eq('telegram_id',tid).maybeSingle();if(!u){const{data:r,error}=await sb.rpc('register_telegram_user',{p_telegram_id:tid,p_first_name:'User',p_last_name:null,p_username:null,p_photo_url:null,p_referral_code:null});if(error)throw error;u=r?.user}return u}
async function invite(m:any,u:any){const[{data:r},{data:s}]=await Promise.all([sb.from('referrals').select('is_verified,points_earned').eq('referrer_id',u.id),sb.from('settings').select('key,value').in('key',['points_per_referral','referral_required_tasks','referral_required_ads'])]);const set=Object.fromEntries((s||[]).map((x:any)=>[x.key,String(x.value)])),all=r||[],qualified=all.filter((x:any)=>x.is_verified).length,earned=all.reduce((a:any,x:any)=>a+Number(x.points_earned||0),0),reward=Number(set.points_per_referral||500),tasks=Number(set.referral_required_tasks||5),ads=Number(set.referral_required_ads||5);const link=`https://t.me/Adsrewartsbot/app?startapp=${u.telegram_id}`;const share=`https://t.me/share/url?url=${encodeURIComponent(link)}&text=${encodeURIComponent('Join AdsReward and earn ADR')}`;await send(m.chat.id,`👥 <b>Invite friends and earn</b>\n\nReward per qualified referral: <b>+${fmt(reward)} ADR</b>\nRequirement: ${tasks} task + ${ads} ad\n\nInvited: <b>${all.length}</b>\nQualified: <b>${qualified}</b>\nPending: <b>${Math.max(0,all.length-qualified)}</b>\nEarned: <b>${fmt(earned)} ADR</b>\n\n<code>${esc(link)}</code>`,[[{text:'📤 Share Invite',url:share}]])}
async function task(m:any,u:any){const now=new Date().toISOString();const{data:t}=await sb.from('tasks').select('id,reward_points,is_repeatable,expires_at').eq('is_active',true).neq('task_type','video').or(`expires_at.is.null,expires_at.gt.${now}`).limit(200);const{data:d}=await sb.from('user_tasks').select('task_id,next_available_at,completed_at').eq('user_id',u.id).order('completed_at',{ascending:false});const latest=new Map();for(const x of d||[])if(!latest.has(x.task_id))latest.set(x.task_id,x.next_available_at);const ts=Date.now(),ready=(t||[]).filter((x:any)=>!latest.has(x.id)||(x.is_repeatable&&(!latest.get(x.id)||new Date(latest.get(x.id)).getTime()<=ts))),reward=ready.reduce((a:any,x:any)=>a+Number(x.reward_points||0),0);await send(m.chat.id,ready.length?`🎯 <b>Tasks available</b>\n\n<b>${ready.length}</b> tasks ready now.\nAvailable rewards: <b>${fmt(reward)} ADR</b>`:'✅ <b>All available tasks are completed.</b>')}
Deno.serve(async(req:Request)=>{try{if(req.method==='GET')return json({success:true,service:'telegram-group-commands',version:'v1-no-app-url-buttons'});if(req.method!=='POST')return json({handled:false},405);if(!same(await secret(),req.headers.get('x-telegram-bot-api-secret-token')||''))return json({handled:false},401);const u=await req.json().catch(()=>({})),m=u.message;if(!m?.from||m.from.is_bot||!['group','supergroup'].includes(String(m.chat?.type))||!m.text)return json({handled:false});const cmd=String(m.text).trim().split(/\s+/)[0].split('@')[0].toLowerCase();if(!['/invite','/task'].includes(cmd))return json({handled:false});const user=await getUser(Number(m.from.id));if(!user)return json({handled:true});if(cmd==='/invite')await invite(m,user);else await task(m,user);return json({handled:true})}catch(e){console.error('telegram-group-commands',e);return json({handled:false,error:String(e.message||e)},500)}});