// @ts-nocheck
import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.55.0";

const URL = Deno.env.get('SUPABASE_URL') || '';
const KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') || '';
const TOKEN = Deno.env.get('TELEGRAM_BOT_TOKEN') || Deno.env.get('BOT_TOKEN') || '';
const APP = 'https://t.me/Adsrewartsbot/app';
const sb = createClient(URL, KEY, { auth: { persistSession: false, autoRefreshToken: false } });
const json = (data:any,status=200)=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json'}});
const esc = (v:any)=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
const b = (text:string, callback_data:string)=>({text, callback_data});
const r = (...x:any[])=>x;
const fmt = (n:any)=>Number(n||0).toLocaleString('en-US');
const ist = (v:any)=>new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Kolkata',day:'2-digit',month:'short',year:'numeric',hour:'numeric',minute:'2-digit',hour12:true}).format(new Date(v));

async function tg(method:string,payload:any){
  const res=await fetch(`https://api.telegram.org/bot${TOKEN}/${method}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});
  const body=await res.json().catch(()=>({ok:false,description:'Bad Telegram response'}));
  if(!res.ok||!body.ok) throw new Error(body.description||`Telegram ${method} failed`);
  return body.result;
}
async function expectedSecret(){const{data}=await sb.rpc('get_bot_internal_secret',{p_name:'adsreward_telegram_webhook_secret'});return String(data||'')}
async function adminIds(){const{data}=await sb.from('settings').select('value').eq('key','bot_admin_telegram_ids').maybeSingle();return new Set(String(data?.value||Deno.env.get('ADMIN_TELEGRAM_ID')||'2139807311').split(',').map((x:string)=>Number(x.trim())).filter(Number.isSafeInteger))}
async function isAdmin(id:number){return (await adminIds()).has(id)}
async function sess(id:number){const{data}=await sb.from('admin_bot_sessions').select('state').eq('admin_telegram_id',id).maybeSingle();return data?.state||{}}
async function setSess(id:number,state:any){await sb.from('admin_bot_sessions').upsert({admin_telegram_id:id,state,updated_at:new Date().toISOString()},{onConflict:'admin_telegram_id'})}
async function clearSess(id:number){await setSess(id,{})}
async function audit(admin:number,action:string,targetUserId:string|null,details:any){await sb.from('admin_logs').insert({admin_telegram_id:admin,action,target_user_id:targetUserId,details})}
async function send(chat:number,text:string,kb:any[][]=[],messageId?:number){
  const payload:any={chat_id:chat,text,parse_mode:'HTML',disable_web_page_preview:true,reply_markup:{inline_keyboard:kb}};
  if(messageId){payload.message_id=messageId;try{return await tg('editMessageText',payload)}catch{delete payload.message_id}}
  return tg('sendMessage',payload);
}
async function ack(id:string,text=''){try{await tg('answerCallbackQuery',{callback_query_id:id,text})}catch{}}
const BACK=r(b('⬅️ Back','adm:main'));
const MAIN=[
  r(b('📊 Dashboard','adm:dashboard'),b('👥 Users','adm:users')),
  r(b('🎯 Tasks','adm:tasks'),b('🎁 Promo Codes','adm:promos')),
  r(b('💸 Withdrawals','adm:withdrawals'),b('📢 Broadcast','adm:broadcast')),
  r(b('🏆 Leaderboard','adm:leaderboard'),b('👥 Referrals','adm:referrals')),
  r(b('📺 Ads','adm:ads'),b('🎮 Rewards','adm:rewards')),
  r(b('🛡 Moderation','adm:moderation'),b('⚙️ Settings','adm:settings')),
  r(b('📜 Logs','adm:logs'),b('🔧 System','adm:system')),
];
async function c(table:string, fn?:(q:any)=>any){let q=sb.from(table).select('*',{count:'exact',head:true});if(fn)q=fn(q);const{count}=await q;return count||0}
async function sumBalances(){const{data}=await sb.from('balances').select('total_earned,total_withdrawn');return (data||[]).reduce((a:any,x:any)=>({earned:a.earned+Number(x.total_earned||0),withdrawn:a.withdrawn+Number(x.total_withdrawn||0)}),{earned:0,withdrawn:0})}
async function dashboard(chat:number,mid?:number){
  const start=new Date();start.setUTCHours(0,0,0,0);const day=start.toISOString();
  const vals=await Promise.all([
    c('users'),c('users',q=>q.gte('created_at',day)),c('users',q=>q.gte('last_active_at',day)),
    c('withdrawals',q=>q.eq('status','pending')),c('withdrawals',q=>q.eq('status','paid')),c('withdrawals',q=>q.eq('status','rejected')),
    c('ad_logs',q=>q.gte('created_at',day)),c('user_tasks',q=>q.gte('completed_at',day)),c('promo_claims',q=>q.gte('claimed_at',day)),
    c('referrals'),c('users',q=>q.eq('is_banned',true)),sumBalances()
  ]);
  const [total,newToday,active,pending,paid,rejected,ads,tasks,promos,refs,banned,bal]=vals as any;
  const text=`📊 <b>AdsReward Dashboard</b>\n\n👥 Total users: <b>${fmt(total)}</b>\n🆕 New today: ${fmt(newToday)}\n🟢 Active today: ${fmt(active)}\n\n💎 ADR issued: ${fmt(bal.earned)}\n💸 ADR withdrawn: ${fmt(bal.withdrawn)}\n⏳ Pending: ${pending} · ✅ Paid: ${paid} · ❌ Rejected: ${rejected}\n\n📺 Ads today: ${fmt(ads)}\n🎯 Tasks today: ${fmt(tasks)}\n🎁 Promo claims: ${fmt(promos)}\n👥 Referrals: ${fmt(refs)}\n🚫 Banned: ${fmt(banned)}`;
  return send(chat,text,[r(b('🔄 Refresh','adm:dashboard'),b('📈 Full Stats','adm:dashboard')),BACK],mid);
}
async function userSearchResults(chat:number,q:string,mid?:number){
  let query=sb.from('users').select('telegram_id,first_name,last_name,username,is_banned').limit(10);
  const cleaned=q.trim().replace(/^@/,'');const id=Number(cleaned);
  if(Number.isSafeInteger(id)&&id>0)query=query.eq('telegram_id',id);else query=query.or(`username.ilike.%${cleaned}%,first_name.ilike.%${cleaned}%,last_name.ilike.%${cleaned}%`);
  const{data}=await query;const kb=(data||[]).map((u:any)=>r(b(`${u.is_banned?'🚫 ':''}${[u.first_name,u.last_name].filter(Boolean).join(' ')}${u.username?' · @'+u.username:''}`,`adm:user:${u.telegram_id}`)));kb.push(BACK);
  return send(chat,data?.length?'👥 <b>User Search Results</b>':'No matching users.',kb,mid);
}
async function userView(chat:number,tid:number,mid?:number){
  const{data:u}=await sb.from('users').select('*').eq('telegram_id',tid).maybeSingle();if(!u)return send(chat,'User not found.',[BACK],mid);
  const [{data:bal},refs,tasks,ads,wds,promos]=await Promise.all([
    sb.from('balances').select('*').eq('user_id',u.id).maybeSingle(),c('referrals',q=>q.eq('referrer_id',u.id)),c('user_tasks',q=>q.eq('user_id',u.id)),c('ad_logs',q=>q.eq('user_id',u.id)),c('withdrawals',q=>q.eq('user_id',u.id)),c('promo_claims',q=>q.eq('user_id',u.id))
  ]);
  const text=`👤 <b>${esc([u.first_name,u.last_name].filter(Boolean).join(' ')||'User')}</b>${u.username?` · @${esc(u.username)}`:''}\nID: <code>${u.telegram_id}</code>\n\n💎 Balance: <b>${fmt(bal?.points)} ADR</b>\n📈 Total earned: ${fmt(bal?.total_earned)}\n💸 Total withdrawn: ${fmt(bal?.total_withdrawn)}\n👥 Referrals: ${refs}\n🎯 Tasks: ${tasks} · 📺 Ads: ${ads}\n🎁 Promo claims: ${promos} · 🧾 Withdrawals: ${wds}\n\n🚫 Banned: ${u.is_banned?'Yes':'No'}\n💸 Withdrawals disabled: ${u.withdrawals_disabled?'Yes':'No'}\n🎁 Rewards disabled: ${u.rewards_disabled?'Yes':'No'}\n👥 Referral rewards disabled: ${u.referral_rewards_disabled?'Yes':'No'}${u.admin_note?`\n📝 Note: ${esc(u.admin_note)}`:''}`;
  const kb=[
    r(b('➕ Add ADR',`adm:bal:add:${tid}`),b('➖ Deduct ADR',`adm:bal:deduct:${tid}`)),
    r(b(u.is_banned?'✅ Unban':'🚫 Ban',`adm:useract:ban:${tid}`),b('📝 Note',`adm:usernote:${tid}`)),
    r(b(u.withdrawals_disabled?'✅ Enable Withdraw':'⛔ Disable Withdraw',`adm:useract:withdraw:${tid}`),b(u.rewards_disabled?'✅ Enable Rewards':'⛔ Disable Rewards',`adm:useract:rewards:${tid}`)),
    r(b(u.referral_rewards_disabled?'✅ Enable Referral Rewards':'⛔ Disable Referral Rewards',`adm:useract:referral:${tid}`)),
    r(b('🔄 Refresh',`adm:user:${tid}`)),BACK
  ];
  return send(chat,text,kb,mid);
}
async function taskMenu(chat:number,mid?:number){const{data}=await sb.from('tasks').select('id,title,reward_points,is_active,is_featured').order('display_order').limit(10);const lines=(data||[]).map((x:any)=>`${x.is_active?'🟢':'⚫'} ${esc(x.title)} · ${fmt(x.reward_points)} ADR${x.is_featured?' ⭐':''}`).join('\n')||'No tasks.';return send(chat,`🎯 <b>Task Management</b>\n\n${lines}`,[r(b('➕ Add Task','adm:task:add'),b('📋 Manage','adm:task:list')),BACK],mid)}
async function taskList(chat:number,mid?:number){const{data}=await sb.from('tasks').select('id,title,is_active').order('display_order').limit(20);const kb=(data||[]).map((x:any)=>r(b(`${x.is_active?'🟢':'⚫'} ${x.title.slice(0,30)}`,`adm:task:view:${x.id}`)));kb.push(BACK);return send(chat,'🎯 <b>Select Task</b>',kb,mid)}
async function taskView(chat:number,id:string,mid?:number){const{data:t}=await sb.from('tasks').select('*').eq('id',id).maybeSingle();if(!t)return send(chat,'Task not found.',[BACK],mid);const text=`🎯 <b>${esc(t.title)}</b>\n\nCategory: ${esc(t.category||t.task_type||'—')}\nDescription: ${esc(t.description||'—')}\nLink: ${esc(t.link||'—')}\nReward: ${fmt(t.reward_points)} ADR\nTotal limit: ${t.total_completion_limit??'Unlimited'}\nPer-user limit: ${t.per_user_limit}\nExpiry: ${t.expires_at?ist(t.expires_at):'None'}\nVerification: ${esc(t.verification_type)}\nOrder: ${t.display_order}\nActive: ${t.is_active?'Yes':'No'} · Featured: ${t.is_featured?'Yes':'No'}`;const kb=[r(b(t.is_active?'⏸ Disable':'▶️ Enable',`adm:task:toggle:${id}`),b(t.is_featured?'☆ Unfeature':'⭐ Feature',`adm:task:feature:${id}`)),r(b('✏️ Edit','adm:task:edit:'+id),b('🗑 Delete','adm:task:deleteask:'+id)),r(b('⬆️ Move Up','adm:task:up:'+id),b('⬇️ Move Down','adm:task:down:'+id)),r(b('⬅️ Tasks','adm:tasks'))];return send(chat,text,kb,mid)}
async function promoMenu(chat:number,mid?:number){const{data}=await sb.from('promos').select('*').order('created_at',{ascending:false}).limit(10);const lines=(data||[]).map((x:any)=>`${x.is_active?'🟢':'⚫'} <code>${esc(x.code)}</code> · ${fmt(x.reward_points)} ADR · ${x.total_claimed}/${x.max_claims}`).join('\n')||'No promo codes.';return send(chat,`🎁 <b>Promo Codes</b>\n\n${lines}`,[r(b('🎲 Generate','adm:promo:generate'),b('✍️ Custom','adm:promo:custom')),r(b('📋 Manage','adm:promo:list')),BACK],mid)}
async function promoList(chat:number,mid?:number){const{data}=await sb.from('promos').select('id,code,is_active').order('created_at',{ascending:false}).limit(20);const kb=(data||[]).map((x:any)=>r(b(`${x.is_active?'🟢':'⚫'} ${x.code}`,`adm:promo:view:${x.id}`)));kb.push(BACK);return send(chat,'🎁 <b>Select Promo</b>',kb,mid)}
async function promoView(chat:number,id:string,mid?:number){const{data:p}=await sb.from('promos').select('*').eq('id',id).maybeSingle();if(!p)return send(chat,'Promo not found.',[BACK],mid);const claims=await c('promo_claims',q=>q.eq('promo_id',id));const text=`🎁 <b>${esc(p.code)}</b>\n\nReward: ${fmt(p.reward_points)} ADR\nClaims: ${claims}/${p.max_claims}\nPer-user: ${p.per_user_limit}\nExpiry: ${p.expires_at?ist(p.expires_at):'Never'}\nActive: ${p.is_active?'Yes':'No'}`;return send(chat,text,[r(b(p.is_active?'⏸ Disable':'▶️ Enable',`adm:promo:toggle:${id}`),b('🗑 Delete','adm:promo:deleteask:'+id)),r(b('👥 Claimers','adm:promo:claimers:'+id)),r(b('⬅️ Promos','adm:promos'))],mid)}
async function withdrawalMenu(chat:number,mid?:number){const [p,a,paid,rej]=await Promise.all(['pending','approved','paid','rejected'].map(s=>c('withdrawals',q=>q.eq('status',s))));return send(chat,`💸 <b>Withdrawals</b>\n\n⏳ Pending: ${p}\n🟦 Approved: ${a}\n✅ Paid: ${paid}\n❌ Rejected: ${rej}`,[r(b('⏳ Pending','adm:wd:list:pending'),b('🟦 Approved','adm:wd:list:approved')),r(b('✅ Paid','adm:wd:list:paid'),b('❌ Rejected','adm:wd:list:rejected')),r(b('🔎 Search','adm:wd:search'),b('↻ Retry Failed Logs','adm:wd:retryall')),BACK],mid)}
async function wdList(chat:number,status:string,mid?:number){const{data}=await sb.from('withdrawals').select('id,public_id,points_spent,method,created_at').eq('status',status).order('created_at',{ascending:false}).limit(15);const kb=(data||[]).map((w:any)=>r(b(`${w.public_id||w.id.slice(0,8)} · ${fmt(w.points_spent)} ADR`,`adm:wd:view:${w.id}`)));kb.push(r(b('⬅️ Withdrawals','adm:withdrawals')));return send(chat,`💸 <b>${status.toUpperCase()}</b>`,kb,mid)}
async function wdView(chat:number,id:string,mid?:number){const{data:w}=await sb.from('withdrawals').select('*,users(first_name,last_name,username,telegram_id)').eq('id',id).maybeSingle();if(!w)return send(chat,'Withdrawal not found.',[BACK],mid);const u:any=w.users||{};const text=`💸 <b>${esc(w.public_id||w.id)}</b>\n\n👤 ${esc([u.first_name,u.last_name].filter(Boolean).join(' ')||'User')} · <code>${u.telegram_id||''}</code>\n💎 ${fmt(w.points_spent)} ADR → ${esc(w.amount)}\nMethod: ${esc(w.method)}\nDestination: <code>${esc(w.wallet_address||'—')}</code>\nStatus: <b>${esc(w.status)}</b>${w.txid?`\nTXID: <code>${esc(w.txid)}</code>`:''}${w.payment_reference?`\nReference: <code>${esc(w.payment_reference)}</code>`:''}${w.rejection_reason?`\nReason: ${esc(w.rejection_reason)}`:''}`;const kb:any[][]=[];if(w.status==='pending')kb.push(r(b('✅ Approve','adm:wd:approveask:'+id),b('❌ Reject','adm:wd:reject:'+id)));if(w.status==='approved')kb.push(r(b('💸 Mark Paid','adm:wd:paid:'+id)));if(['paid','rejected'].includes(w.status))kb.push(r(b('↻ Retry Log','adm:wd:retry:'+id)));kb.push(r(b('⬅️ Withdrawals','adm:withdrawals')));return send(chat,text,kb,mid)}
async function referrals(chat:number,mid?:number){const [total,valid,flagged]=await Promise.all([c('referrals'),c('referrals',q=>q.eq('is_verified',true)),c('referrals',q=>q.eq('is_flagged',true))]);const{data:rows}=await sb.from('referrals').select('referrer_id,points_earned');const issued=(rows||[]).reduce((a:any,x:any)=>a+Number(x.points_earned||0),0);const freq=new Map();for(const x of rows||[])freq.set(x.referrer_id,(freq.get(x.referrer_id)||0)+1);let top='';for(const[id,n]of [...freq.entries()].sort((a:any,b:any)=>b[1]-a[1]).slice(0,5)){const{data:u}=await sb.from('users').select('first_name,username,telegram_id').eq('id',id).maybeSingle();if(u)top+=`\n${n} · ${esc(u.first_name)}${u.username?' @'+esc(u.username):' '+u.telegram_id}`};return send(chat,`👥 <b>Referral Management</b>\n\nTotal: ${total}\n✅ Valid: ${valid}\n❌ Invalid: ${total-valid}\n🚩 Flagged: ${flagged}\n💎 Rewards issued: ${fmt(issued)} ADR\n\n<b>Top Referrers</b>${top||'\n—'}`,[r(b('💎 Reward','adm:set:points_per_referral'),b('🧪 Validation','adm:ref:rules')),r(b('🔎 Inspect User Tree','adm:ref:search')),BACK],mid)}
async function ads(chat:number,mid?:number){const providers=['adsgram','monetag','gigapub'];const keys=providers.flatMap(p=>[`${p}_max_ads_per_day`,`${p}_max_ads_per_hour`,`${p}_cooldown_seconds`]).concat(['ad_reward_points']);const{data:s}=await sb.from('settings').select('key,value').in('key',keys);const m=Object.fromEntries((s||[]).map((x:any)=>[x.key,x.value]));const start=new Date();start.setUTCHours(0,0,0,0);const{data:logs}=await sb.from('ad_logs').select('provider,reward_given').gte('created_at',start.toISOString());const st:any={};for(const x of logs||[]){const p=x.provider||'unknown';st[p]=st[p]||{i:0,r:0};st[p].i++;st[p].r+=Number(x.reward_given||0)}let text='📺 <b>Ads Management</b>\n';for(const p of providers)text+=`\n${p}: ${st[p]?.i||0} views · ${fmt(st[p]?.r||0)} ADR\nDaily ${m[p+'_max_ads_per_day']||0} · Hourly ${m[p+'_max_ads_per_hour']||m.max_ads_per_hour||10} · ${m[p+'_cooldown_seconds']||0}s`;text+=`\n\nReward: ${m.ad_reward_points||0} ADR`;return send(chat,text,[r(b('AdsGram','adm:ad:adsgram'),b('Monetag','adm:ad:monetag')),r(b('GigaPub','adm:ad:gigapub'),b('💎 Reward','adm:set:ad_reward_points')),r(b('⛔ Disable All Ads','adm:ad:disableask')),BACK],mid)}
async function rewards(chat:number,mid?:number){const keys=['daily_drop_base','farm_reward_points','ad_reward_points','points_per_referral','promo_default_reward','achievement_ads_reward','spin_reward_max','contest_max_winners'];const{data}=await sb.from('settings').select('key,value').in('key',keys);const m=Object.fromEntries((data||[]).map((x:any)=>[x.key,x.value]));return send(chat,`🎮 <b>Reward Settings</b>\n\n🎁 Daily: ${m.daily_drop_base} ADR\n🌾 Farming: ${m.farm_reward_points} ADR\n📺 Ad: ${m.ad_reward_points} ADR\n👥 Referral: ${m.points_per_referral} ADR\n🎟 Promo default: ${m.promo_default_reward} ADR\n🏅 Achievement: ${m.achievement_ads_reward} ADR\n🍀 Lucky draw max: ${m.spin_reward_max} ADR\n🏆 Winner count: ${m.contest_max_winners}`,[r(b('🎁 Daily','adm:set:daily_drop_base'),b('🌾 Farming','adm:set:farm_reward_points')),r(b('📺 Ad','adm:set:ad_reward_points'),b('👥 Referral','adm:set:points_per_referral')),r(b('🎟 Promo','adm:set:promo_default_reward'),b('🏅 Achievement','adm:set:achievement_ads_reward')),r(b('🍀 Lucky','adm:set:spin_reward_max'),b('🏆 Winners','adm:set:contest_max_winners')),BACK],mid)}
async function leaderboard(chat:number,mid?:number){const{data:active}=await sb.from('contests').select('*').eq('is_active',true).order('created_at',{ascending:false}).limit(1).maybeSingle();let text='🏆 <b>Leaderboard</b>\n';if(active){text+=`\nRound: ${esc(active.title)}\nType: ${esc(active.contest_type)}\nEnds: ${ist(active.ends_at)}\nWinners: ${active.winner_count||5}\n`;const{data:e}=await sb.from('contest_entries').select('score,user_id').eq('contest_id',active.id).order('score',{ascending:false}).limit(10);let i=0;for(const x of e||[]){i++;const{data:u}=await sb.from('users').select('first_name,username').eq('id',x.user_id).maybeSingle();text+=`\n${i}. ${esc(u?.first_name||'User')} · ${fmt(x.score)}`}}else{text+='\nNo active round.'}const{data:prev}=await sb.from('contests').select('id,title,ends_at').eq('is_active',false).order('ends_at',{ascending:false}).limit(3);if(prev?.length){text+='\n\nPrevious:';for(const p of prev)text+=`\n• ${esc(p.title)} · ${ist(p.ends_at)}`};return send(chat,text,[r(b('➕ Start Round','adm:lb:start'),b('⏹ End Round','adm:lb:endask')),r(b('👑 Winner Count','adm:set:contest_max_winners'),b('🔄 Refresh','adm:leaderboard')),BACK],mid)}
async function moderation(chat:number,mid?:number){const [ban,wd,rw,rr,flag]=await Promise.all([c('users',q=>q.eq('is_banned',true)),c('users',q=>q.eq('withdrawals_disabled',true)),c('users',q=>q.eq('rewards_disabled',true)),c('users',q=>q.eq('referral_rewards_disabled',true)),c('referrals',q=>q.eq('is_flagged',true))]);return send(chat,`🛡 <b>Moderation</b>\n\n🚫 Banned: ${ban}\n💸 Withdrawal blocked: ${wd}\n🎁 Reward blocked: ${rw}\n👥 Referral reward blocked: ${rr}\n🚩 Flagged referrals: ${flag}`,[r(b('🔎 Search User','adm:user:search'),b('🚩 Referrals','adm:referrals')),BACK],mid)}
const toggles=['maintenance_mode','withdrawal_enabled','registration_enabled','promo_claims_enabled','referral_system_enabled','withdraw_upi_enabled','withdraw_usdt_polygon_enabled','withdraw_ton_enabled'];
async function settings(chat:number,mid?:number){const keys=toggles.concat(['min_withdrawal_points','max_withdrawal_points','usdt_conversion_rate','inr_conversion_rate','support_username','payout_channel','admin_alert_chat_id','bot_default_language','app_announcement_text']);const{data}=await sb.from('settings').select('key,value').in('key',keys);const m=Object.fromEntries((data||[]).map((x:any)=>[x.key,x.value]));const on=(k:string)=>String(m[k]||'false')==='true'?'🟢':'🔴';return send(chat,`⚙️ <b>Settings</b>\n\n${on('maintenance_mode')} Maintenance\n${on('withdrawal_enabled')} Withdrawals\n${on('registration_enabled')} Registration\n${on('promo_claims_enabled')} Promo claims\n${on('referral_system_enabled')} Referrals\n\nMin withdraw: ${m.min_withdrawal_points||'—'} ADR\nMax withdraw: ${m.max_withdrawal_points||'—'} ADR\nUSDT rate: ${m.usdt_conversion_rate||'—'}\nINR rate: ${m.inr_conversion_rate||'—'}\nSupport: ${esc(m.support_username||'—')}\nPayout: ${esc(m.payout_channel||'—')}\nAdmin alert: ${esc(m.admin_alert_chat_id||'—')}`,[r(b('🛠 Maintenance','adm:toggle:maintenance_mode'),b('💸 Withdrawals','adm:toggle:withdrawal_enabled')),r(b('👤 Registration','adm:toggle:registration_enabled'),b('🎁 Promo Claims','adm:toggle:promo_claims_enabled')),r(b('👥 Referrals','adm:toggle:referral_system_enabled'),b('🇮🇳 UPI','adm:toggle:withdraw_upi_enabled')),r(b('💵 USDT','adm:toggle:withdraw_usdt_polygon_enabled'),b('💎 TON','adm:toggle:withdraw_ton_enabled')),r(b('Min Withdraw','adm:set:min_withdrawal_points'),b('Max Withdraw','adm:set:max_withdrawal_points')),r(b('USDT Rate','adm:set:usdt_conversion_rate'),b('INR Rate','adm:set:inr_conversion_rate')),r(b('Support','adm:set:support_username'),b('Payout Channel','adm:set:payout_channel')),r(b('Admin Alert','adm:set:admin_alert_chat_id'),b('Announcement','adm:set:app_announcement_text')),BACK],mid)}
async function logs(chat:number,mid?:number){const{data}=await sb.from('admin_logs').select('*').order('created_at',{ascending:false}).limit(12);const text=(data||[]).map((x:any)=>`<b>${esc(x.action)}</b> · ${x.admin_telegram_id}\n${ist(x.created_at)} · ${esc(JSON.stringify(x.details||{}).slice(0,120))}`).join('\n\n')||'No logs.';return send(chat,`📜 <b>Admin Logs</b>\n\n${text}`,[r(b('🔄 Refresh','adm:logs')),BACK],mid)}
async function system(chat:number,mid?:number){const [failed,chats]=await Promise.all([c('withdrawal_log_deliveries',q=>q.eq('delivery_status','failed')),c('telegram_bot_chats',q=>q.eq('is_active',true))]);let telegram='✅';try{await tg('getMe',{})}catch{telegram='❌'}const{data:last}=await sb.from('withdrawal_log_deliveries').select('delivery_error,updated_at').eq('delivery_status','failed').order('updated_at',{ascending:false}).limit(1).maybeSingle();return send(chat,`🔧 <b>System</b>\n\n🤖 Bot: ✅\n🗄 Database: ✅\n📱 Mini App: ✅\n✈️ Telegram API: ${telegram}\n❌ Failed log deliveries: ${failed}\n💬 Registered admin chats: ${chats}${last?`\n\nLast error: ${esc(last.delivery_error)}\n${ist(last.updated_at)}`:''}`,[r(b('↻ Retry Logs','adm:wd:retryall'),b('🔄 Refresh Permissions','adm:sys:permissions')),r(b('🔗 Check Integrations','adm:system')),BACK],mid)}
async function broadcastMenu(chat:number,mid?:number){const{data}=await sb.from('broadcasts').select('*').order('sent_at',{ascending:false}).limit(5);const lines=(data||[]).map((x:any)=>`${x.status==='completed'?'✅':x.status==='sending'?'🟡':'⚪'} ${ist(x.sent_at)} · ${esc(x.target)} · ${x.sent_count||0}/${(x.sent_count||0)+(x.failed_count||0)}`).join('\n')||'No broadcasts.';return send(chat,`📢 <b>Broadcast</b>\n\n${lines}`,[r(b('➕ Create','adm:bc:create')),BACK],mid)}
async function startSetting(admin:number,chat:number,key:string,mid?:number){const{data}=await sb.from('settings').select('value').eq('key',key).maybeSingle();await setSess(admin,{flow:'setting_value',key,current:data?.value||''});return send(chat,`⚙️ <b>Change Setting</b>\n\n${esc(key)}\nCurrent: <code>${esc(data?.value||'')}</code>\n\nSend the new value.`,[BACK],mid)}
async function processBroadcast(id:string){
  const{data:bc}=await sb.from('broadcasts').select('*').eq('id',id).single();if(!bc)return;
  await sb.from('broadcasts').update({status:'sending'}).eq('id',id);
  let q=sb.from('users').select('telegram_id,bot_language,last_active_at').eq('is_banned',false);
  if(bc.target==='active')q=q.gte('last_active_at',new Date(Date.now()-7*86400000).toISOString());
  if(bc.target==='language'&&bc.language_filter)q=q.eq('bot_language',bc.language_filter);
  if(bc.target==='ids'&&bc.target_ids?.length)q=q.in('telegram_id',bc.target_ids);
  const{data:users}=await q.limit(5000);let sent=0,failed=0;
  for(const u of users||[]){try{const base:any={chat_id:u.telegram_id,parse_mode:'HTML'};if(bc.buttons?.length)base.reply_markup={inline_keyboard:bc.buttons};if(bc.media_type==='photo')await tg('sendPhoto',{...base,photo:bc.telegram_file_id,caption:bc.message||''});else if(bc.media_type==='video')await tg('sendVideo',{...base,video:bc.telegram_file_id,caption:bc.message||''});else if(bc.media_type==='animation')await tg('sendAnimation',{...base,animation:bc.telegram_file_id,caption:bc.message||''});else await tg('sendMessage',{...base,text:bc.message||' '});sent++}catch{failed++}if((sent+failed)%25===0)await new Promise(res=>setTimeout(res,1000))}
  await sb.from('broadcasts').update({status:'completed',sent_count:sent,failed_count:failed,completed_at:new Date().toISOString()}).eq('id',id);
}

async function handleText(admin:number,chat:number,msg:any){
  const s=await sess(admin);if(!s.flow)return false;const text=String(msg.text||msg.caption||'').trim();if(text==='/cancel'){await clearSess(admin);await send(chat,'Cancelled.',MAIN);return true}
  if(s.flow==='user_search'){await clearSess(admin);await userSearchResults(chat,text);return true}
  if(s.flow==='balance_amount'){const n=Math.floor(Number(text));if(!Number.isSafeInteger(n)||n<=0){await send(chat,'Send a positive whole ADR amount.');return true}await setSess(admin,{...s,flow:'balance_reason',amount:n});await send(chat,'📝 Send the reason.');return true}
  if(s.flow==='balance_reason'){if(text.length<2){await send(chat,'Reason is required.');return true}await setSess(admin,{...s,flow:'balance_confirm',reason:text});await send(chat,`⚠️ <b>Confirm Balance Change</b>\n\nUser: <code>${s.tid}</code>\n${s.mode==='add'?'+':'-'}${fmt(s.amount)} ADR\nReason: ${esc(text)}`,[r(b('✅ Confirm','adm:bal:confirm'),b('❌ Cancel','adm:cancel'))]);return true}
  if(s.flow==='user_note'){await setSess(admin,{...s,flow:'user_note_confirm',note:text});await send(chat,`📝 <b>Confirm Note</b>\n\n${esc(text)}`,[r(b('✅ Save','adm:note:confirm'),b('❌ Cancel','adm:cancel'))]);return true}
  if(s.flow==='setting_value'){await setSess(admin,{...s,flow:'setting_confirm',next:text});await send(chat,`⚠️ <b>Confirm Setting</b>\n\n${esc(s.key)}\nCurrent: <code>${esc(s.current)}</code>\nNew: <code>${esc(text)}</code>`,[r(b('✅ Confirm','adm:set:confirm'),b('❌ Cancel','adm:cancel'))]);return true}
  if(s.flow==='wd_search'){const{data:w}=await sb.from('withdrawals').select('id').eq('public_id',text).maybeSingle();await clearSess(admin);if(w)await wdView(chat,w.id);else await send(chat,'Withdrawal not found.',[BACK]);return true}
  if(s.flow==='wd_reject_reason'){if(text.length<3){await send(chat,'Reason is required.');return true}await setSess(admin,{...s,flow:'wd_reject_confirm',reason:text});await send(chat,`❌ <b>Confirm Rejection</b>\n\nReason: ${esc(text)}\nNo ADR refund.`,[r(b('✅ Confirm Reject','adm:wd:rejectconfirm'),b('❌ Cancel','adm:cancel'))]);return true}
  if(s.flow==='wd_paid_ref'){if(!text){await send(chat,'TXID/UTR/reference is required.');return true}await setSess(admin,{...s,flow:'wd_paid_confirm',reference:text});await send(chat,`💸 <b>Confirm Paid</b>\n\nReference: <code>${esc(text)}</code>`,[r(b('✅ Confirm Paid','adm:wd:paidconfirm'),b('❌ Cancel','adm:cancel'))]);return true}
  if(s.flow==='task_step'){
    const fields=['category','title','description','link','reward','totalLimit','perUser','expiry','verification'];const idx=s.idx||0;const field=fields[idx];const data={...(s.data||{})};if(['reward','totalLimit','perUser'].includes(field)&&(!Number.isFinite(Number(text))||Number(text)<0)){await send(chat,'Send a valid number.');return true}data[field]=text;if(idx<fields.length-1){const prompts=['Title?','Description?','Link?','ADR reward?','Total completion limit? (0 = unlimited)','Per-user limit?','Expiry? ISO date/time or 0','Verification type?'];await setSess(admin,{flow:'task_step',idx:idx+1,data});await send(chat,`Step ${idx+2}/${fields.length} · ${prompts[idx]}`)}else{await setSess(admin,{flow:'task_confirm',data});await send(chat,`🎯 <b>Task Preview</b>\n\nCategory: ${esc(data.category)}\nTitle: ${esc(data.title)}\nDescription: ${esc(data.description)}\nLink: ${esc(data.link)}\nReward: ${esc(data.reward)} ADR\nTotal limit: ${esc(data.totalLimit)}\nPer-user: ${esc(data.perUser)}\nExpiry: ${esc(data.expiry)}\nVerification: ${esc(data.verification)}`,[r(b('✅ Create','adm:task:confirm'),b('❌ Cancel','adm:cancel'))])}return true
  }
  if(s.flow==='task_edit_field'){await setSess(admin,{...s,flow:'task_edit_confirm',next:text});await send(chat,`⚠️ Confirm task update\n\n${esc(s.field)} → ${esc(text)}`,[r(b('✅ Confirm','adm:task:editconfirm'),b('❌ Cancel','adm:cancel'))]);return true}
  if(s.flow==='promo_step'){
    const fields=s.custom?['code','reward','maxClaims','perUser','expiry']:['reward','maxClaims','perUser','expiry'];const idx=s.idx||0,field=fields[idx],data={...(s.data||{})};if(['reward','maxClaims','perUser'].includes(field)&&(!Number.isFinite(Number(text))||Number(text)<=0)){await send(chat,'Send a positive number.');return true}data[field]=text;if(idx<fields.length-1){const next=fields[idx+1];const prompts:any={reward:'ADR reward?',maxClaims:'Total claim limit?',perUser:'Per-user claim limit?',expiry:'Expiry? ISO date/time or 0'};await setSess(admin,{...s,flow:'promo_step',idx:idx+1,data});await send(chat,prompts[next]||'Promo code?')}else{await setSess(admin,{flow:'promo_confirm',data});await send(chat,`🎁 <b>Promo Preview</b>\n\nCode: <code>${esc(data.code)}</code>\nReward: ${data.reward} ADR\nTotal limit: ${data.maxClaims}\nPer-user: ${data.perUser}\nExpiry: ${esc(data.expiry)}`,[r(b('✅ Create','adm:promo:confirm'),b('❌ Cancel','adm:cancel'))])}return true
  }
  if(s.flow==='bc_content'){
    const media=msg.photo?.at(-1)?.file_id?{type:'photo',fileId:msg.photo.at(-1).file_id}:msg.video?.file_id?{type:'video',fileId:msg.video.file_id}:msg.animation?.file_id?{type:'animation',fileId:msg.animation.file_id}:{type:'text',fileId:null};const content={message:msg.text||msg.caption||'',mediaType:media.type,fileId:media.fileId,buttons:[]};await setSess(admin,{flow:'bc_preview',content});await send(chat,`📢 <b>Broadcast Preview</b>\n\nType: ${media.type}\n${esc(content.message||'(media only)')}\n\nChoose audience.`,[r(b('👥 All','adm:bc:target:all'),b('🟢 Active','adm:bc:target:active')),r(b('🌐 Language','adm:bc:targetlang'),b('🎯 User IDs','adm:bc:targetids')),r(b('❌ Cancel','adm:cancel'))]);return true
  }
  if(s.flow==='bc_language'){await setSess(admin,{...s,flow:'bc_confirm',target:'language',language:text.toLowerCase()});await send(chat,`📢 Send broadcast to language <b>${esc(text)}</b>?`,[r(b('✅ Confirm Send','adm:bc:send'),b('❌ Cancel','adm:cancel'))]);return true}
  if(s.flow==='bc_ids'){const ids=text.split(/[ ,\n]+/).map(Number).filter(Number.isSafeInteger);if(!ids.length){await send(chat,'Send one or more Telegram IDs.');return true}await setSess(admin,{...s,flow:'bc_confirm',target:'ids',ids});await send(chat,`📢 Send to ${ids.length} specific users?`,[r(b('✅ Confirm Send','adm:bc:send'),b('❌ Cancel','adm:cancel'))]);return true}
  if(s.flow==='lb_start_title'){await setSess(admin,{...s,flow:'lb_start_type',title:text});await send(chat,'Leaderboard type? e.g. ads / referrals / points');return true}
  if(s.flow==='lb_start_type'){await setSess(admin,{...s,flow:'lb_start_hours',type:text});await send(chat,'Duration in hours?');return true}
  if(s.flow==='lb_start_hours'){const h=Number(text);if(!Number.isFinite(h)||h<=0){await send(chat,'Send valid hours.');return true}await setSess(admin,{...s,flow:'lb_start_prizes',hours:h});await send(chat,'Send top-5 ADR prizes comma-separated, e.g. 2000,1200,800,600,400');return true}
  if(s.flow==='lb_start_prizes'){const p=text.split(',').map(x=>Math.floor(Number(x.trim())));if(p.some(x=>!Number.isSafeInteger(x)||x<0)||p.length<1){await send(chat,'Invalid prize list.');return true}while(p.length<5)p.push(0);await setSess(admin,{...s,flow:'lb_start_confirm',prizes:p.slice(0,5)});await send(chat,`🏆 <b>Round Preview</b>\n\n${esc(s.title)} · ${esc(s.type)}\nDuration: ${s.hours}h\nPrizes: ${p.slice(0,5).join(', ')} ADR`,[r(b('✅ Start Round','adm:lb:startconfirm'),b('❌ Cancel','adm:cancel'))]);return true}
  return false;
}

async function handleCb(admin:number,chat:number,mid:number,cb:any){
  const d=String(cb.data||'');await ack(cb.id);
  if(d==='adm:main'){await clearSess(admin);return send(chat,'🛠 <b>AdsReward Admin</b>\n\nChoose a management area.',MAIN,mid)}
  if(d==='adm:dashboard')return dashboard(chat,mid);
  if(d==='adm:users')return send(chat,'👥 <b>User Management</b>\n\nSearch users and manage balances, moderation, referrals and history.',[r(b('🔎 Search User','adm:user:search')),BACK],mid);
  if(d==='adm:user:search'){await setSess(admin,{flow:'user_search'});return send(chat,'🔎 Send Telegram ID, @username or name.',[BACK],mid)}
  if(d.startsWith('adm:user:')&&!d.startsWith('adm:useract:'))return userView(chat,Number(d.split(':')[2]),mid);
  if(d.startsWith('adm:bal:')){const[, ,mode,tid]=d.split(':');if(mode==='confirm'){const s=await sess(admin);if(s.flow!=='balance_confirm')return send(chat,'Confirmation expired.',[BACK],mid);const{data:u}=await sb.from('users').select('id').eq('telegram_id',s.tid).single();const delta=(s.mode==='add'?1:-1)*Number(s.amount);const{error}=await sb.rpc('admin_adjust_balance_atomic',{p_user_id:u.id,p_delta:delta,p_reason:s.reason,p_admin_telegram_id:admin});if(error)throw error;await clearSess(admin);return userView(chat,s.tid,mid)}await setSess(admin,{flow:'balance_amount',mode,tid:Number(tid)});return send(chat,'💎 Send ADR amount.',[BACK],mid)}
  if(d.startsWith('adm:useract:')){const[, ,act,tidRaw]=d.split(':');const tid=Number(tidRaw);const{data:u}=await sb.from('users').select('*').eq('telegram_id',tid).single();let patch:any={},action='';if(act==='ban'){patch={is_banned:!u.is_banned,ban_reason:!u.is_banned?'Admin moderation':null};action=!u.is_banned?'user_banned':'user_unbanned'}if(act==='withdraw'){patch={withdrawals_disabled:!u.withdrawals_disabled};action='withdrawal_access_toggled'}if(act==='rewards'){patch={rewards_disabled:!u.rewards_disabled};action='reward_access_toggled'}if(act==='referral'){patch={referral_rewards_disabled:!u.referral_rewards_disabled};action='referral_reward_access_toggled'}await sb.from('users').update(patch).eq('id',u.id);await audit(admin,action,u.id,{before:{is_banned:u.is_banned,withdrawals_disabled:u.withdrawals_disabled,rewards_disabled:u.rewards_disabled,referral_rewards_disabled:u.referral_rewards_disabled},after:patch});return userView(chat,tid,mid)}
  if(d.startsWith('adm:usernote:')){await setSess(admin,{flow:'user_note',tid:Number(d.split(':')[2])});return send(chat,'📝 Send internal admin note.',[BACK],mid)}
  if(d==='adm:note:confirm'){const s=await sess(admin);if(s.flow!=='user_note_confirm')return;const{data:u}=await sb.from('users').select('id,admin_note').eq('telegram_id',s.tid).single();await sb.from('users').update({admin_note:s.note.slice(0,1000)}).eq('id',u.id);await audit(admin,'user_note',u.id,{before:u.admin_note,after:s.note.slice(0,1000)});await clearSess(admin);return userView(chat,s.tid,mid)}

  if(d==='adm:tasks')return taskMenu(chat,mid);if(d==='adm:task:list')return taskList(chat,mid);if(d==='adm:task:add'){await setSess(admin,{flow:'task_step',idx:0,data:{}});return send(chat,'🎯 <b>Add Task</b>\n\nStep 1/9 · Category?',[BACK],mid)}if(d.startsWith('adm:task:view:'))return taskView(chat,d.slice('adm:task:view:'.length),mid);
  if(d.startsWith('adm:task:toggle:')||d.startsWith('adm:task:feature:')){const isToggle=d.startsWith('adm:task:toggle:'),id=d.slice(isToggle?'adm:task:toggle:'.length:'adm:task:feature:'.length),field=isToggle?'is_active':'is_featured';const{data:t}=await sb.from('tasks').select(field).eq('id',id).single();await sb.from('tasks').update({[field]:!t[field],updated_at:new Date().toISOString()}).eq('id',id);await audit(admin,'task_update',null,{taskId:id,field,before:t[field],after:!t[field]});return taskView(chat,id,mid)}
  if(d.startsWith('adm:task:edit:')){const id=d.slice('adm:task:edit:'.length);return send(chat,'✏️ <b>Edit Task</b>',[r(b('Title','adm:task:field:title:'+id),b('Description','adm:task:field:description:'+id)),r(b('Link','adm:task:field:link:'+id),b('Reward','adm:task:field:reward_points:'+id)),r(b('Total Limit','adm:task:field:total_completion_limit:'+id),b('Per-user','adm:task:field:per_user_limit:'+id)),r(b('Expiry','adm:task:field:expires_at:'+id),b('Verification','adm:task:field:verification_type:'+id)),r(b('⬅️ Task','adm:task:view:'+id))],mid)}
  if(d.startsWith('adm:task:field:')){const rest=d.slice('adm:task:field:'.length),i=rest.indexOf(':'),field=rest.slice(0,i),id=rest.slice(i+1);await setSess(admin,{flow:'task_edit_field',id,field});return send(chat,`Send new value for <b>${esc(field)}</b>. Use 0 for no expiry/limit where applicable.`,[BACK],mid)}
  if(d==='adm:task:editconfirm'){const s=await sess(admin);if(s.flow!=='task_edit_confirm')return;const allowed=['title','description','link','reward_points','total_completion_limit','per_user_limit','expires_at','verification_type'];if(!allowed.includes(s.field))throw new Error('Invalid task field');const{data:t}=await sb.from('tasks').select(s.field).eq('id',s.id).single();let val:any=s.next;if(['reward_points','total_completion_limit','per_user_limit'].includes(s.field))val=Number(val);if(s.field==='total_completion_limit'&&Number(val)===0)val=null;if(s.field==='expires_at')val=String(val)==='0'?null:new Date(val).toISOString();await sb.from('tasks').update({[s.field]:val,updated_at:new Date().toISOString()}).eq('id',s.id);await audit(admin,'task_update',null,{taskId:s.id,field:s.field,before:t[s.field],after:val});await clearSess(admin);return taskView(chat,s.id,mid)}
  if(d.startsWith('adm:task:deleteask:'))return send(chat,'⚠️ Delete this task permanently?',[r(b('🗑 Confirm Delete','adm:task:delete:'+d.slice('adm:task:deleteask:'.length)),b('Cancel','adm:tasks'))],mid);
  if(d.startsWith('adm:task:delete:')){const id=d.slice('adm:task:delete:'.length);const{data:t}=await sb.from('tasks').select('*').eq('id',id).single();await sb.from('tasks').delete().eq('id',id);await audit(admin,'task_deleted',null,{task:t});return taskMenu(chat,mid)}
  if(d.startsWith('adm:task:up:')||d.startsWith('adm:task:down:')){const up=d.startsWith('adm:task:up:'),id=d.slice(up?'adm:task:up:'.length:'adm:task:down:'.length);const{data:t}=await sb.from('tasks').select('display_order').eq('id',id).single();await sb.from('tasks').update({display_order:Number(t.display_order||0)+(up?-1:1)}).eq('id',id);await audit(admin,'task_reordered',null,{taskId:id,before:t.display_order,after:Number(t.display_order||0)+(up?-1:1)});return taskView(chat,id,mid)}
  if(d==='adm:task:confirm'){const s=await sess(admin);if(s.flow!=='task_confirm')return;const x=s.data;const expiry=String(x.expiry)==='0'?null:new Date(x.expiry).toISOString();const{data:t,error}=await sb.from('tasks').insert({category:x.category,task_type:x.category,title:x.title,description:x.description,link:x.link,reward_points:Number(x.reward),total_completion_limit:Number(x.totalLimit)>0?Number(x.totalLimit):null,per_user_limit:Math.max(1,Number(x.perUser)),expires_at:expiry,verification_type:x.verification,is_active:true,is_featured:false,display_order:999,is_repeatable:false}).select('id').single();if(error)throw error;await audit(admin,'task_created',null,{taskId:t.id,...x});await clearSess(admin);return taskView(chat,t.id,mid)}

  if(d==='adm:promos')return promoMenu(chat,mid);if(d==='adm:promo:list')return promoList(chat,mid);if(d==='adm:promo:generate'||d==='adm:promo:custom'){const custom=d.endsWith('custom'),code=custom?'':crypto.randomUUID().replaceAll('-','').slice(0,8).toUpperCase();await setSess(admin,{flow:'promo_step',idx:0,custom,data:{code}});return send(chat,custom?'Send custom promo code.':`Generated: <code>${code}</code>\n\nSend ADR reward.`,[BACK],mid)}if(d.startsWith('adm:promo:view:'))return promoView(chat,d.slice('adm:promo:view:'.length),mid);
  if(d.startsWith('adm:promo:toggle:')){const id=d.slice('adm:promo:toggle:'.length);const{data:p}=await sb.from('promos').select('is_active').eq('id',id).single();await sb.from('promos').update({is_active:!p.is_active,updated_at:new Date().toISOString()}).eq('id',id);await audit(admin,'promo_toggle',null,{promoId:id,before:p.is_active,after:!p.is_active});return promoView(chat,id,mid)}
  if(d.startsWith('adm:promo:deleteask:'))return send(chat,'⚠️ Delete this promo permanently?',[r(b('🗑 Confirm','adm:promo:delete:'+d.slice('adm:promo:deleteask:'.length)),b('Cancel','adm:promos'))],mid);
  if(d.startsWith('adm:promo:delete:')){const id=d.slice('adm:promo:delete:'.length);const{data:p}=await sb.from('promos').select('*').eq('id',id).single();await sb.from('promos').delete().eq('id',id);await audit(admin,'promo_deleted',null,{promo:p});return promoMenu(chat,mid)}
  if(d.startsWith('adm:promo:claimers:')){const id=d.slice('adm:promo:claimers:'.length);const{data}=await sb.from('promo_claims').select('claimed_at,users(first_name,username,telegram_id)').eq('promo_id',id).order('claimed_at',{ascending:false}).limit(20);const lines=(data||[]).map((x:any)=>`${esc(x.users?.first_name||'User')} · ${x.users?.username?'@'+esc(x.users.username):x.users?.telegram_id} · ${ist(x.claimed_at)}`).join('\n')||'No claims.';return send(chat,`👥 <b>Promo Claimers</b>\n\n${lines}`,[r(b('⬅️ Promos','adm:promos'))],mid)}
  if(d==='adm:promo:confirm'){const s=await sess(admin);if(s.flow!=='promo_confirm')return;const x=s.data,code=String(x.code).trim().toUpperCase();if(!/^[A-Z0-9_-]{3,32}$/.test(code))return send(chat,'Invalid promo code format.',[BACK],mid);const expiry=String(x.expiry)==='0'?null:new Date(x.expiry).toISOString();const{data:p,error}=await sb.from('promos').insert({code,title:`Promo ${code}`,reward_points:Number(x.reward),max_claims:Number(x.maxClaims),per_user_limit:Number(x.perUser),total_claimed:0,is_active:true,expires_at:expiry}).select('id').single();if(error)throw error;await audit(admin,'promo_created',null,{promoId:p.id,...x});await clearSess(admin);return promoView(chat,p.id,mid)}

  if(d==='adm:withdrawals')return withdrawalMenu(chat,mid);if(d.startsWith('adm:wd:list:'))return wdList(chat,d.slice('adm:wd:list:'.length),mid);if(d.startsWith('adm:wd:view:'))return wdView(chat,d.slice('adm:wd:view:'.length),mid);if(d==='adm:wd:search'){await setSess(admin,{flow:'wd_search'});return send(chat,'Send withdrawal ID, e.g. #ADR-10287.',[BACK],mid)}
  if(d.startsWith('adm:wd:approveask:'))return send(chat,'⚠️ Approve this withdrawal?',[r(b('✅ Confirm Approve','adm:wd:approve:'+d.slice('adm:wd:approveask:'.length)),b('Cancel','adm:withdrawals'))],mid);
  if(d.startsWith('adm:wd:approve:')){const id=d.slice('adm:wd:approve:'.length);const{error}=await sb.rpc('process_withdrawal_admin',{p_withdrawal_id:id,p_action:'approve',p_admin_telegram_id:admin,p_admin_name:'Telegram Admin',p_txid:null,p_payment_reference:null,p_rejection_reason:null,p_fee:0});if(error)throw error;return wdView(chat,id,mid)}
  if(d.startsWith('adm:wd:reject:')){await setSess(admin,{flow:'wd_reject_reason',id:d.slice('adm:wd:reject:'.length)});return send(chat,'❌ Send rejection reason.',[BACK],mid)}
  if(d==='adm:wd:rejectconfirm'){const s=await sess(admin);if(s.flow!=='wd_reject_confirm')return;const{error}=await sb.rpc('process_withdrawal_admin',{p_withdrawal_id:s.id,p_action:'reject',p_admin_telegram_id:admin,p_admin_name:'Telegram Admin',p_txid:null,p_payment_reference:null,p_rejection_reason:s.reason,p_fee:0});if(error)throw error;const id=s.id;await clearSess(admin);return wdView(chat,id,mid)}
  if(d.startsWith('adm:wd:paid:')){await setSess(admin,{flow:'wd_paid_ref',id:d.slice('adm:wd:paid:'.length)});return send(chat,'💸 Send TXID / UTR / payment reference.',[BACK],mid)}
  if(d==='adm:wd:paidconfirm'){const s=await sess(admin);if(s.flow!=='wd_paid_confirm')return;const{data:w}=await sb.from('withdrawals').select('method').eq('id',s.id).single();const{error}=await sb.rpc('process_withdrawal_admin',{p_withdrawal_id:s.id,p_action:'paid',p_admin_telegram_id:admin,p_admin_name:'Telegram Admin',p_txid:w.method==='upi'?null:s.reference,p_payment_reference:w.method==='upi'?s.reference:null,p_rejection_reason:null,p_fee:0});if(error)throw error;const id=s.id;await clearSess(admin);return wdView(chat,id,mid)}
  if(d.startsWith('adm:wd:retry:')){const id=d.slice('adm:wd:retry:'.length);return send(chat,'↻ Use Retry Log from the final withdrawal record; status and balance are never changed by retries.',[r(b('⬅️ Withdrawal','adm:wd:view:'+id))],mid)}
  if(d==='adm:wd:retryall'){const{data}=await sb.from('withdrawal_log_deliveries').select('withdrawal_id').eq('delivery_status','failed').limit(50);const ids=[...new Set((data||[]).map((x:any)=>x.withdrawal_id))];return send(chat,`↻ Failed delivery records: ${ids.length}\n\nOpen individual final withdrawals and retry their log safely.`,[r(b('⬅️ Withdrawals','adm:withdrawals'))],mid)}

  if(d==='adm:broadcast')return broadcastMenu(chat,mid);if(d==='adm:bc:create'){await setSess(admin,{flow:'bc_content'});return send(chat,'Send text, photo, video or animation. Caption is supported.\n\nYou will preview before sending.',[BACK],mid)}if(d.startsWith('adm:bc:target:')){const s=await sess(admin);if(s.flow!=='bc_preview')return;const target=d.slice('adm:bc:target:'.length);await setSess(admin,{...s,flow:'bc_confirm',target});return send(chat,`📢 Send this broadcast to <b>${esc(target)}</b> users?`,[r(b('✅ Confirm Send','adm:bc:send'),b('❌ Cancel','adm:cancel'))],mid)}if(d==='adm:bc:targetlang'){const s=await sess(admin);await setSess(admin,{...s,flow:'bc_language'});return send(chat,'Send language code, e.g. en, hi, ru.',[BACK],mid)}if(d==='adm:bc:targetids'){const s=await sess(admin);await setSess(admin,{...s,flow:'bc_ids'});return send(chat,'Send Telegram IDs separated by spaces/commas.',[BACK],mid)}
  if(d==='adm:bc:send'){const s=await sess(admin);if(s.flow!=='bc_confirm')return;const x=s.content;const{data:bc,error}=await sb.from('broadcasts').insert({message:x.message||'',sent_by:admin,sent_at:new Date().toISOString(),target:s.target,media_type:x.mediaType,telegram_file_id:x.fileId,buttons:x.buttons||[],status:'queued',language_filter:s.language||null,target_ids:s.ids||null}).select('id').single();if(error)throw error;await audit(admin,'broadcast_created',null,{broadcastId:bc.id,target:s.target,language:s.language||null,targetCount:s.ids?.length||null,mediaType:x.mediaType});await clearSess(admin);const task=processBroadcast(bc.id);try{(globalThis as any).EdgeRuntime?.waitUntil(task)}catch{void task}return send(chat,`📢 <b>Broadcast Queued</b>\n\nID: <code>${bc.id}</code>\nTarget: ${esc(s.target)}\n\nDelivery counts will update in Broadcast history.`,[r(b('📢 Broadcasts','adm:broadcast')),BACK],mid)}

  if(d==='adm:leaderboard')return leaderboard(chat,mid);if(d==='adm:lb:start'){await setSess(admin,{flow:'lb_start_title'});return send(chat,'🏆 Send round title.',[BACK],mid)}if(d==='adm:lb:startconfirm'){const s=await sess(admin);if(s.flow!=='lb_start_confirm')return;const now=new Date(),ends=new Date(now.getTime()+Number(s.hours)*3600000);const p=s.prizes;const{data:ct,error}=await sb.from('contests').insert({contest_type:s.type,title:s.title,description:'Created from Telegram admin',starts_at:now.toISOString(),ends_at:ends.toISOString(),is_active:true,reward_1st:p[0]||0,reward_2nd:p[1]||0,reward_3rd:p[2]||0,reward_4th:p[3]||0,reward_5th:p[4]||0,winner_count:Math.min(5,p.filter((x:number)=>x>0).length||5),duration_hours:Number(s.hours),reward_method:'ADR',rewards_distributed:false}).select('id').single();if(error)throw error;await audit(admin,'leaderboard_round_started',null,{contestId:ct.id,title:s.title,type:s.type,hours:s.hours,prizes:p});await clearSess(admin);return leaderboard(chat,mid)}if(d==='adm:lb:endask')return send(chat,'⚠️ End the active leaderboard round?',[r(b('⏹ Confirm End','adm:lb:end'),b('Cancel','adm:leaderboard'))],mid);if(d==='adm:lb:end'){const{data:ct}=await sb.from('contests').select('id,title').eq('is_active',true).order('created_at',{ascending:false}).limit(1).maybeSingle();if(!ct)return leaderboard(chat,mid);await sb.from('contests').update({is_active:false,ends_at:new Date().toISOString()}).eq('id',ct.id);await audit(admin,'leaderboard_round_ended',null,{contestId:ct.id,title:ct.title});return leaderboard(chat,mid)}

  if(d==='adm:referrals')return referrals(chat,mid);if(d==='adm:ref:rules')return send(chat,'👥 <b>Referral Validation Rules</b>',[r(b('Required Ads','adm:set:referral_required_ads'),b('Required Tasks','adm:set:referral_required_tasks')),r(b('Reward','adm:set:points_per_referral'),b('Referred Bonus','adm:set:referral_bonus_referred')),r(b('⬅️ Referrals','adm:referrals'))],mid);if(d==='adm:ref:search'){await setSess(admin,{flow:'user_search'});return send(chat,'Send referrer Telegram ID, @username or name.',[BACK],mid)}
  if(d==='adm:ads')return ads(chat,mid);if(d.startsWith('adm:ad:')&&!d.startsWith('adm:ad:disable')&&!d.startsWith('adm:ad:toggle:')){const p=d.slice('adm:ad:'.length);const keys=[`${p}_max_ads_per_day`,`${p}_max_ads_per_hour`,`${p}_cooldown_seconds`];const{data}=await sb.from('settings').select('key,value').in('key',keys);const m=Object.fromEntries((data||[]).map((x:any)=>[x.key,x.value]));return send(chat,`📺 <b>${esc(p)}</b>\n\nDaily limit: ${m[keys[0]]||0}\nHourly limit: ${m[keys[1]]||10}\nCooldown: ${m[keys[2]]||0}s`,[r(b('Daily Limit','adm:set:'+keys[0]),b('Hourly Limit','adm:set:'+keys[1])),r(b('Cooldown','adm:set:'+keys[2]),b(Number(m[keys[0]]||0)>0?'⛔ Disable':'✅ Enable',`adm:ad:toggle:${p}`)),r(b('⬅️ Ads','adm:ads'))],mid)}if(d.startsWith('adm:ad:toggle:')){const p=d.slice('adm:ad:toggle:'.length),k=`${p}_max_ads_per_day`;const{data:x}=await sb.from('settings').select('value').eq('key',k).maybeSingle();const next=Number(x?.value||0)>0?'0':'10';await sb.from('settings').upsert({key:k,value:next,updated_at:new Date().toISOString()},{onConflict:'key'});await audit(admin,'ad_provider_toggle',null,{provider:p,before:x?.value,after:next});return ads(chat,mid)}if(d==='adm:ad:disableask')return send(chat,'⚠️ Disable AdsGram, Monetag and GigaPub?',[r(b('⛔ Confirm','adm:ad:disableall'),b('Cancel','adm:ads'))],mid);if(d==='adm:ad:disableall'){for(const p of['adsgram','monetag','gigapub'])await sb.from('settings').upsert({key:`${p}_max_ads_per_day`,value:'0',updated_at:new Date().toISOString()},{onConflict:'key'});await audit(admin,'all_ads_disabled',null,{});return ads(chat,mid)}
  if(d==='adm:rewards')return rewards(chat,mid);if(d==='adm:moderation')return moderation(chat,mid);if(d==='adm:settings')return settings(chat,mid);if(d.startsWith('adm:toggle:')){const key=d.slice('adm:toggle:'.length);if(!toggles.includes(key))throw new Error('Unsupported toggle');const{data:x}=await sb.from('settings').select('value').eq('key',key).maybeSingle();const next=String(x?.value)==='true'?'false':'true';await sb.from('settings').upsert({key,value:next,updated_at:new Date().toISOString()},{onConflict:'key'});await audit(admin,'setting_toggle',null,{key,before:x?.value,after:next});return settings(chat,mid)}if(d.startsWith('adm:set:')&&d!=='adm:set:confirm')return startSetting(admin,chat,d.slice('adm:set:'.length),mid);if(d==='adm:set:confirm'){const s=await sess(admin);if(s.flow!=='setting_confirm')return;const{data:x}=await sb.from('settings').select('value').eq('key',s.key).maybeSingle();await sb.from('settings').upsert({key:s.key,value:String(s.next),updated_at:new Date().toISOString()},{onConflict:'key'});await audit(admin,'setting_update',null,{key:s.key,before:x?.value,after:String(s.next)});await clearSess(admin);return settings(chat,mid)}
  if(d==='adm:logs')return logs(chat,mid);if(d==='adm:system')return system(chat,mid);if(d==='adm:sys:permissions'){const{data:chats}=await sb.from('telegram_bot_chats').select('chat_id,chat_type').eq('is_active',true);const bot=await tg('getMe',{});let ok=0,bad=0;for(const ch of chats||[]){try{const m=await tg('getChatMember',{chat_id:ch.chat_id,user_id:bot.id});const adminStatus=['administrator','creator'].includes(String(m.status));await sb.from('telegram_bot_chats').update({is_admin:adminStatus,bot_member_status:m.status,can_send_messages:adminStatus&&ch.chat_type!=='channel',can_post_messages:adminStatus&&ch.chat_type==='channel'&&m.can_post_messages!==false,last_verified_at:new Date().toISOString()}).eq('chat_id',ch.chat_id);adminStatus?ok++:bad++}catch{bad++}}return send(chat,`🔄 Permissions refreshed.\n\n✅ Admin/sendable: ${ok}\n❌ Not sendable: ${bad}`,[r(b('⬅️ System','adm:system'))],mid)}
  if(d==='adm:cancel'){await clearSess(admin);return send(chat,'Cancelled.',MAIN,mid)}
}

Deno.serve(async(req:Request)=>{
  try{
    if(req.method!=='POST')return json({handled:false});
    const secret=await expectedSecret();if(secret&&req.headers.get('x-telegram-bot-api-secret-token')!==secret)return json({handled:false,error:'unauthorized'},401);
    const u=await req.json().catch(()=>({}));const from=u.callback_query?.from||u.message?.from;if(!from)return json({handled:false});const admin=Number(from.id);if(!(await isAdmin(admin)))return json({handled:false});const chat=Number(u.callback_query?.message?.chat?.id||u.message?.chat?.id);if(!chat)return json({handled:false});
    if(u.callback_query&&String(u.callback_query.data||'').startsWith('adm:')){await handleCb(admin,chat,Number(u.callback_query.message.message_id),u.callback_query);return json({handled:true})}
    const text=String(u.message?.text||'');if(text==='/admin'||text.startsWith('/admin@')){await clearSess(admin);await send(chat,'🛠 <b>AdsReward Admin</b>\n\nComplete Telegram management panel.',MAIN);return json({handled:true})}
    const state=await sess(admin);if(state.flow){await handleText(admin,chat,u.message);return json({handled:true})}
    return json({handled:false});
  }catch(e){console.error('telegram-admin',e);return json({handled:true,error:(e as Error).message})}
});