ALTER TABLE contests
  ADD COLUMN IF NOT EXISTS description    TEXT,
  ADD COLUMN IF NOT EXISTS reward_method  TEXT DEFAULT 'points',
  ADD COLUMN IF NOT EXISTS banner_emoji   TEXT DEFAULT '🏆',
  ADD COLUMN IF NOT EXISTS winner_count   INTEGER DEFAULT 5,
  ADD COLUMN IF NOT EXISTS duration_hours INTEGER DEFAULT 24;
