import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.55.0";
const URL=Deno.env.get('SUPABASE_URL')||'';
const KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';
const TOKEN=Deno.env.get('TELEGRAM_BOT_TOKEN')||'';
const sb=createClient(URL,KEY,{auth:{persistSession:false,autoRefreshToken:false}});
const json=(d:any,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{'Content-Type':'application/json'}});
async function secret(){const{data,error}=await sb.rpc('get_bot_internal_secret',{p_name:'adsreward_telegram_webhook_secret'});if(error||!data)throw error||new Error('Missing secret');return String(data)}
async function tg(method:string,payload:any){const r=await fetch(`https://api.telegram.org/bot${TOKEN}/${method}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const b=await r.json().catch(()=>({ok:false}));if(!r.ok||!b.ok)throw new Error(b.description||method);return b.result}
Deno.serve(async(req:Request)=>{try{if(req.method==='GET'){if(new URL(req.url).searchParams.get('sync')==='1'){const wh=await secret();await tg('setWebhook',{url:`${URL}/functions/v1/telegram-router`,secret_token:wh,allowed_updates:['message','callback_query','channel_post','my_chat_member'],drop_pending_updates:false});return json({success:true,syncedTo:'telegram-router'});}return json({success:true,service:'telegram-group-router',mode:'forward-only'});}if(req.method!=='POST')return json({success:false},405);const body=await req.text();const h:Record<string,string>={'Content-Type':'application/json'};const s=req.headers.get('x-telegram-bot-api-secret-token');if(s)h['x-telegram-bot-api-secret-token']=s;const r=await fetch(`${URL}/functions/v1/telegram-router`,{method:'POST',headers:h,body});return new Response(await r.text(),{status:r.status,headers:{'Content-Type':'application/json'}});}catch(e){return json({success:false,error:(e as Error).message},500)}});